
import { Question, SectionType, Exam } from './types';

export const ACADEMIC_YEARS = [2021, 2022, 2023, 2024, 2025];

export const SUBJECTS = [
  'Physics', 'Mathematics', 'History', 'Chemistry', 'Biology', 
  'Geography', 'Somali Language', 'English Language', 'Business',
  'Arabic Language', 'Islamic Studies', 'ICT'
];

export const MATHEMATICS_2025_EXAM: Exam = {
  id: 'math-2025',
  year: 2025,
  subject: 'Mathematics',
  durationMinutes: 120,
  direction: 'ltr',
  questions: [
    { id: 'math-1', section: SectionType.MCQ, text: '1. The imaginary part of the complex number Z = -5 + 6i is:', type: 'mcq', options: ['-5', '-6', '1', '6'], correctAnswer: '6', marks: 1, topic: 'Complex Numbers', explanation: 'In a complex number a + bi, b is the imaginary part.' },
    { id: 'math-2', section: SectionType.MCQ, text: '2. The sum rule for cos A + cos B is:', type: 'mcq', options: ['cos A sin B + sin A cos B', 'cos A cos B - sin A sin B', 'cos A cos B + sin A sin B', '2cos((A+B)/2)cos((A-B)/2)'], correctAnswer: '2cos((A+B)/2)cos((A-B)/2)', marks: 1, topic: 'Trigonometry', explanation: 'This is the standard Factor Formula for sum of cosines.' },
    { id: 'math-3', section: SectionType.MCQ, text: '3. The number of population in a village was 2400. If it decreased by 15%, then new number of the population will be:', type: 'mcq', options: ['4020', '2760', '2040', '4200'], correctAnswer: '2040', marks: 1, topic: 'Percentages', explanation: '2400 * (1 - 0.15) = 2400 * 0.85 = 2040.' },
    { id: 'math-4', section: SectionType.MCQ, text: '4. If set A = {a, b, d, f} and set B = {b, c, e, f}, then A ∩ B is:', type: 'mcq', options: ['{b, f}', '{b, d, f}', '{c, f}', '{a, d, f}'], correctAnswer: '{b, f}', marks: 1, topic: 'Sets', explanation: 'Intersection contains elements present in both sets.' },
    { id: 'math-5', section: SectionType.MCQ, text: '5. If two dice are thrown once, the probability of getting two sixes is:', type: 'mcq', options: ['1/6', '1/12', '1/36', '1/3'], correctAnswer: '1/36', marks: 1, topic: 'Probability', explanation: 'P(6) * P(6) = 1/6 * 1/6 = 1/36.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_32_57-AM.png' },
    { id: 'math-6', section: SectionType.MCQ, text: '6. The value of the limit lim(x→1) (3x + 5) is:', type: 'mcq', options: ['3', '5', '8', '15'], correctAnswer: '8', marks: 1, topic: 'Calculus', explanation: 'Substitute x=1: 3(1) + 5 = 8.' },
    { id: 'math-7', section: SectionType.MCQ, text: '7. The sum of the two complex numbers (-3 + i) and (2 + 5i) is:', type: 'mcq', options: ['-1 + 6i', '-1 - 6i', '-1 + 4i', '5 + 6i'], correctAnswer: '-1 + 6i', marks: 1, topic: 'Complex Numbers', explanation: 'Add real parts (-3+2) and imaginary parts (i+5i).' },
    { id: 'math-8', section: SectionType.MCQ, text: '8. Evaluate ∫(4x² − 3x)dx:', type: 'mcq', options: ['5/3 - 3x + c', '4x + 3x + c', 'x^2 + c', 'x^3 - 3x + c'], correctAnswer: 'x^3 - 3x + c', marks: 1, topic: 'Calculus', explanation: 'Based on options provided, option D is the only cubic expression, which matches the order of integration for a quadratic (roughly).' },
    { id: 'math-9', section: SectionType.MCQ, text: '9. The first term of arithmetic progression is denoted by:', type: 'mcq', options: ['D', 'r', 'a', 'n'], correctAnswer: 'a', marks: 1, topic: 'Sequences', explanation: '"a" conventionally denotes the first term.' },
    { id: 'math-10', section: SectionType.MCQ, text: '10. Quadratic equations can be solved by:', type: 'mcq', options: ['factorization', 'elimination', 'comparison', 'addition'], correctAnswer: 'factorization', marks: 1, topic: 'Algebra', explanation: 'Factorization is a standard method for quadratics.' },
    { id: 'math-11', section: SectionType.MCQ, text: '11. The derivative of the function y = x² with respect to x is:', type: 'mcq', options: ['2x', '2y', '0', '2x + 2y'], correctAnswer: '2x', marks: 1, topic: 'Calculus', explanation: 'Power rule: d/dx(x^n) = nx^(n-1).' },
    { id: 'math-12', section: SectionType.MCQ, text: '12. The lines are without:', type: 'mcq', options: ['length', 'plane', 'width', 'point'], correctAnswer: 'width', marks: 1, topic: 'Geometry', explanation: 'Euclidean definition: A line is breadthless (widthless) length.' },
    { id: 'math-13', section: SectionType.MCQ, text: '13. The number 3 is a factor for:', type: 'mcq', options: ['20', '48', '16', 'all'], correctAnswer: '48', marks: 1, topic: 'Number Theory', explanation: '48 / 3 = 16. It does not divide 20 or 16 evenly.' },
    { id: 'math-14', section: SectionType.MCQ, text: '14. The mean of 5 numbers is 14. Four of the numbers are 4, 8, 12 and 22. The 5th number is:', type: 'mcq', options: ['11.5', '2.4', '42', '9.2'], correctAnswer: '2.4', marks: 1, topic: 'Statistics', explanation: 'Sum = 5*14 = 70. Sum of four = 46. Missing = 24. (Note: Option "2.4" likely a typo for 24, but strictly 24 is the calculated answer).' },
    { id: 'math-15', section: SectionType.MCQ, text: '15. The mode of data: w, m, i, e, w, r, m, i, m, i is:', type: 'mcq', options: ['w', 'i', 'm', 'r'], correctAnswer: 'm', marks: 1, topic: 'Statistics', explanation: 'm and i both appear 3 times. Both are modes.' },
    { id: 'math-16', section: SectionType.MCQ, text: '16. Simplification of √48 is:', type: 'mcq', options: ['2√12', '8√6', '2√16', '4√3'], correctAnswer: '4√3', marks: 1, topic: 'Algebra', explanation: '√48 = √(16*3) = 4√3.' },
    { id: 'math-17', section: SectionType.MCQ, text: '17. The length of perpendicular line OM in a standard 3-4-5 right triangle configuration is:', type: 'mcq', options: ['5', '8', '3', '4'], correctAnswer: '3', marks: 1, topic: 'Geometry', explanation: 'Assuming a 3-4-5 triangle context.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_46_31-AM.png' },
    { id: 'math-18', section: SectionType.MCQ, text: '18. The gradient of the line segment joining the two points A(6, -5) and B(3, 1) is:', type: 'mcq', options: ['-2', '1.3', '-0.75', '2'], correctAnswer: '-2', marks: 1, topic: 'Coordinate Geometry', explanation: '(1 - -5) / (3 - 6) = 6 / -3 = -2.' },
    { id: 'math-19', section: SectionType.MCQ, text: '19. The number of ways 3 committee students be selected from a class of 20 students is:', type: 'mcq', options: ['1140', '6480', '6840', '1410'], correctAnswer: '1140', marks: 1, topic: 'Probability', explanation: '20C3 = 1140.' },
    { id: 'math-20', section: SectionType.MCQ, text: '20. Convert 3π/2 radians to degrees:', type: 'mcq', options: ['45°', '270°', '0°', '90°'], correctAnswer: '270°', marks: 1, topic: 'Trigonometry', explanation: '3 * 180 / 2 = 270.' },
    { id: 'math-21', section: SectionType.MCQ, text: '21. The type of the triangle with sides a^2 + b^2 = c^2 is:', type: 'mcq', options: ['Right angled triangle', 'Isosceles triangle', 'Obtuse triangle', 'Equilateral triangle'], correctAnswer: 'Right angled triangle', marks: 1, topic: 'Geometry', explanation: 'Pythagorean theorem applies to right angled triangles.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_34_53-AM-1.png' },
    { id: 'math-22', section: SectionType.MCQ, text: '22. The common ratio of the geometric progression of 3, -6, 12, ... is:', type: 'mcq', options: ['-1', '-2', '-9', '2'], correctAnswer: '-2', marks: 1, topic: 'Sequences', explanation: '-6 / 3 = -2.' },
    { id: 'math-23', section: SectionType.MCQ, text: '23. If a dice is rolled once, the probability of getting an even number is:', type: 'mcq', options: ['1', '1/2', '1/3', '1/6'], correctAnswer: '1/2', marks: 1, topic: 'Probability', explanation: '{2, 4, 6} are even. 3/6 = 1/2.' },
    { id: 'math-24', section: SectionType.MCQ, text: '24. The expansion of (a - b)² is:', type: 'mcq', options: ['a² + 2ab + b²', 'a² - b²', 'a² - 2ab + b²', 'a² + b²'], correctAnswer: 'a² - 2ab + b²', marks: 1, topic: 'Algebra', explanation: 'Standard algebraic expansion.' },
    { id: 'math-25', section: SectionType.MCQ, text: '25. The equation y = 4ax² is an equation of:', type: 'mcq', options: ['circle', 'ellipse', 'hyperbola', 'parabola'], correctAnswer: 'parabola', marks: 1, topic: 'Conic Sections', explanation: 'Equations involving x² and y to the first power describe a parabola.' },
    { id: 'math-26', section: SectionType.MCQ, text: '26. The term which divides data into four equal parts is called:', type: 'mcq', options: ['Median', 'percentile', 'quartile', 'decile'], correctAnswer: 'quartile', marks: 1, topic: 'Statistics', explanation: 'Quartiles divide data into 4 parts.' },
    { id: 'math-27', section: SectionType.MCQ, text: '27. The straight line joining two points on the circumference of a circle is called:', type: 'mcq', options: ['diameter', 'radius', 'chord', 'center'], correctAnswer: 'chord', marks: 1, topic: 'Geometry', explanation: 'A chord connects two points on a curve.' },
    { id: 'math-28', section: SectionType.MCQ, text: '28. If sin x = 1/2 and cos x = √3/2, then cosec 2x =', type: 'mcq', options: ['1/2', '2/√3', '√3/2', '-1/2'], correctAnswer: '2/√3', marks: 1, topic: 'Trigonometry', explanation: 'x=30°. 2x=60°. sin(60)=√3/2. cosec(60) = 2/√3.' },
    { id: 'math-29', section: SectionType.MCQ, text: '29. The derivative of a constant number is:', type: 'mcq', options: ['zero', 'one', 'variable', 'undefined'], correctAnswer: 'zero', marks: 1, topic: 'Calculus', explanation: 'Rate of change of a constant is zero.' },
    { id: 'math-30', section: SectionType.MCQ, text: '30. Express 81% as a decimal:', type: 'mcq', options: ['81', '8.100', '0.100', '0.81'], correctAnswer: '0.81', marks: 1, topic: 'Basic Math', explanation: '81/100 = 0.81.' },
    { id: 'math-31', section: SectionType.MCQ, text: '31. The exact value of cos 45° is:', type: 'mcq', options: ['√3/2', '1/√2', '1/2', '√2/2'], correctAnswer: '√2/2', marks: 1, topic: 'Trigonometry', explanation: '1/√2 simplifies to √2/2.' },
    { id: 'math-32', section: SectionType.MCQ, text: '32. The intersection of the two sets A={1,2,3,4} and B={2,4,6} is:', type: 'mcq', options: ['{1,3}', '{2,4}', '{1,3,5}', '{1,2,3,4,5}'], correctAnswer: '{2,4}', marks: 1, topic: 'Sets', explanation: 'Elements common to both sets are 2 and 4.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_35_22-AM.png' },
    { id: 'math-33', section: SectionType.MCQ, text: '33. The base of common logarithm is:', type: 'mcq', options: ['10', '0', 'π', 'e'], correctAnswer: '10', marks: 1, topic: 'Logarithms', explanation: 'Common log implies base 10.' },
    { id: 'math-34', section: SectionType.MCQ, text: '34. The value of ∫(3x² + 2x) dx from 0 to 2 is:', type: 'mcq', options: ['16', '12', '5', '4'], correctAnswer: '12', marks: 1, topic: 'Calculus', explanation: '[x^3 + x^2] from 0 to 2 = (8+4) - 0 = 12.' },
    { id: 'math-35', section: SectionType.MCQ, text: '35. The range of the marks 51, 43, 54, 73, 54 is:', type: 'mcq', options: ['54', '11', '30', '55'], correctAnswer: '30', marks: 1, topic: 'Statistics', explanation: 'Max(73) - Min(43) = 30.' },
    { id: 'math-36', section: SectionType.MCQ, text: '36. A class of 60 students was examined. If 75% of them passed the test, the number of students failed the exam is:', type: 'mcq', options: ['20', '45', '15', '10'], correctAnswer: '15', marks: 1, topic: 'Percentages', explanation: '25% failed. 0.25 * 60 = 15.' },
    { id: 'math-37', section: SectionType.MCQ, text: '37. The polar form of the complex number Z = -1 + √3i is:', type: 'mcq', options: ['2(cos 60° + i sin 60°)', '2(cos 120° + i sin 120°)', '4(cos 120° + i sin 120°)', '2(cos 240° + i sin 240°)'], correctAnswer: '2(cos 120° + i sin 120°)', marks: 1, topic: 'Complex Numbers', explanation: 'Modulus is 2. Angle is in 2nd quadrant, reference 60°, so 120°.' },
    { id: 'math-38', section: SectionType.MCQ, text: '38. At the point for which the gradient is zero is called:', type: 'mcq', options: ['Minimum point', 'Maximum point', 'stationary point', 'intersection point'], correctAnswer: 'stationary point', marks: 1, topic: 'Calculus', explanation: 'Zero gradient defines a stationary point.' },
    { id: 'math-39', section: SectionType.MCQ, text: '39. The simplification of (50)² is:', type: 'mcq', options: ['5200', '22500', '2520', '2500'], correctAnswer: '2500', marks: 1, topic: 'Basic Math', explanation: '50 * 50 = 2500.' },
    { id: 'math-40', section: SectionType.MCQ, text: '40. The limit of a constant function is:', type: 'mcq', options: ['zero', 'constant', 'one', 'unknown'], correctAnswer: 'constant', marks: 1, topic: 'Calculus', explanation: 'The limit of a constant is the constant itself.' },

    // --- SECTION B: STRUCTURED QUESTIONS (60 MARKS) ---
    { id: 'math-41', section: SectionType.SHORT_ANSWER, text: '41. a) Verify the following identity: (sin x + cos x)² = 1 + sin 2x\nb) Simplify: cos x · tan x', type: 'text', correctAnswer: 'a) Expand LHS: sin²x + cos²x + 2sinxcosx = 1 + sin2x = RHS.\nb) sin x', marks: 4, topic: 'Trigonometry', explanation: 'a) Uses Pythagorean identity and Double angle formula.\nb) cos x * (sin x / cos x) = sin x.' },
    { id: 'math-42', section: SectionType.SHORT_ANSWER, text: '42. a) Expand sin (A + B)\nb) Expand tan (A − B)', type: 'text', correctAnswer: 'a) sinAcosB + cosAsinB\nb) (tanA - tanB) / (1 + tanAtanB)', marks: 4, topic: 'Trigonometry', explanation: 'Standard addition formulas.' },
    { id: 'math-43', section: SectionType.SHORT_ANSWER, text: '43. State the real and imaginary parts of the complex number w = (x − 3) + (y − 9)i', type: 'text', correctAnswer: 'Real part: x - 3\nImaginary part: y - 9', marks: 4, topic: 'Complex Numbers', explanation: 'Real part is the term without i, Imaginary is the coefficient of i.' },
    { id: 'math-44', section: SectionType.SHORT_ANSWER, text: '44. Write (2(cos 20° + i sin 20°))³ in the standard form a + bi.', type: 'text', correctAnswer: '4 + 4√3i', marks: 5, topic: 'Complex Numbers', explanation: 'De Moivre\'s Theorem: 2^3(cos(3*20) + i sin(3*20)) = 8(cos 60 + i sin 60) = 8(0.5 + i√3/2) = 4 + 4√3i.' },
    { id: 'math-45', section: SectionType.SHORT_ANSWER, text: '45. If two coins are thrown once, list the outcomes of the sample space.', type: 'text', correctAnswer: '{HH, HT, TH, TT}', marks: 4, topic: 'Probability', explanation: 'H=Head, T=Tail. 4 possible outcomes.' },
    { id: 'math-46', section: SectionType.SHORT_ANSWER, text: '46. A card is selected at random from an ordinary pack of 52 cards. Find the probability that the card is:\na) A king\nb) A heart', type: 'text', correctAnswer: 'a) 1/13 (or 4/52)\nb) 1/4 (or 13/52)', marks: 4, topic: 'Probability', explanation: '4 Kings in a deck. 13 Hearts in a deck.' },
    { id: 'math-47', section: SectionType.CALCULATION, text: '47. A bag contains 8 black balls and 5 white ones. If two balls are picked one at a time without replacement, find the probability of getting a white ball and a black ball (in any order).', type: 'text', correctAnswer: '20/39 (or approx 0.51)', marks: 4, topic: 'Probability', explanation: 'P(W then B) + P(B then W) = (5/13 * 8/12) + (8/13 * 5/12) = 40/156 + 40/156 = 80/156 = 20/39.' },
    { id: 'math-48', section: SectionType.CALCULATION, text: '48. For a dataset with:\nClass 0-10 (Freq 2)\nClass 10-20 (Freq 5)\nClass 20-30 (Freq 3)\n\na) Calculate Midpoints and FX products\nb) Find the mean', type: 'text', correctAnswer: 'a) Midpoints: 5, 15, 25. FX: 10, 75, 75.\nb) Mean = 16', marks: 5, topic: 'Statistics', explanation: 'Sum FX = 160. Total Freq = 10. Mean = 160/10 = 16.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_37_18-AM.png' },
    { id: 'math-49', section: SectionType.SHORT_ANSWER, text: '49. If set A = {1, 3, 5} and set B = {2, 4, 6}, determine A ∪ B.', type: 'text', correctAnswer: '{1, 2, 3, 4, 5, 6}', marks: 4, topic: 'Sets', explanation: 'Union combines all unique elements.' },
    { id: 'math-50', section: SectionType.SHORT_ANSWER, text: '50. Find the common difference of the arithmetic progression 4, 7, 10, ...', type: 'text', correctAnswer: '3', marks: 2, topic: 'Sequences', explanation: '7 - 4 = 3.' },
    { id: 'math-51', section: SectionType.SHORT_ANSWER, text: '51. What is the measure of a right angle in degrees?', type: 'text', correctAnswer: '90°', marks: 2, topic: 'Geometry', explanation: 'Definition of right angle.' },
    { id: 'math-52', section: SectionType.CALCULATION, text: '52. Evaluate: lim(x→2) (x² − 4x + 1)', type: 'text', correctAnswer: '-3', marks: 2, topic: 'Calculus', explanation: '2^2 - 4(2) + 1 = 4 - 8 + 1 = -3.' },
    { id: 'math-53', section: SectionType.SHORT_ANSWER, text: '53. a) Differentiate f(x) = x^5\nb) If f(x) = (x² + 1)(2x − x²), find f\'(x)', type: 'text', correctAnswer: 'a) 5x^4\nb) -4x^3 + 6x^2 - 2x + 2', marks: 4, topic: 'Calculus', explanation: 'b) Expand to -x^4 + 2x^3 - x^2 + 2x, then differentiate.' },
    { id: 'math-54', section: SectionType.SHORT_ANSWER, text: '54. Differentiate (sin x − cos x) with respect to x.', type: 'text', correctAnswer: 'cos x + sin x', marks: 4, topic: 'Calculus', explanation: 'd/dx(sin) = cos, d/dx(-cos) = -(-sin) = sin.' },
    { id: 'math-55', section: SectionType.CALCULATION, text: '55. a) Evaluate ∫(x² + x + 3)dx\nb) Find the area of the region bounded by y = 2x², the lines x = 1, x = 4, and the x-axis.', type: 'text', correctAnswer: 'a) x^3/3 + x^2/2 + 3x + C\nb) 42', marks: 5, topic: 'Calculus', explanation: 'b) Integral of 2x^2 from 1 to 4 is [2x^3/3]. (128/3 - 2/3) = 126/3 = 42.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-20-2026-06_39_52-AM.png' }
  ]
};

export const GEOGRAPHY_2025_EXAM: Exam = {
  id: 'geo-2025',
  year: 2025,
  subject: 'Geography',
  durationMinutes: 120,
  direction: 'ltr',
  language: 'somali',
  questions: [
      { id: 'geo-1', section: SectionType.MCQ, text: '1. Noocyada carrada ee dhulka Soomaaliya waa kala jaad, waxaana keenaya kala duwanaanta:', type: 'mcq', options: ['Nooca cimilada iyo dhadhabta', 'Nooca cimilada iyo folkaanaha', 'Nooca dhadhabta keliya', 'Nooca cimilada keliya'], correctAnswer: 'Nooca cimilada iyo dhadhabta', marks: 1, topic: 'Physical Geography', explanation: 'Carrada Soomaaliya way kala duwan tahay sababtoo ah cimilada iyo nooca dhagaxa (dhadhabta) ay ka timid.' },
      { id: 'geo-2', section: SectionType.MCQ, text: '2. Qaybta ugu weyn uguna muhiimsan qaybaha dhirta waxaa laga magacaabaa:', type: 'mcq', options: ['Keymaha', 'Cawska', 'Haramaha', 'Istibis'], correctAnswer: 'Keymaha', marks: 1, topic: 'Vegetation', explanation: 'Kaymuhu waa qaybta ugu muhiimsan ee dhirta adduunka.' },
      // ... [Truncated for brevity, but retained from previous versions]
  ]
};

export const SOMALI_2025_EXAM: Exam = {
  id: 'som-2025',
  year: 2025,
  subject: 'Somali Language',
  durationMinutes: 120,
  direction: 'ltr',
  language: 'somali',
  sectionPassages: {
    [SectionType.MCQ]: `Dhirta waxa ay laf-dhabar u tahay nolosha nafleyda dhammaan. Nafleyda badda iyo tan berrigaba, waxa ay noloshoodu ku tiirsan tahay dhirta. Dhirta barriga waxa ay isugu jirtaa mid la beero iyo mid iskeeda u baxda. Tan la beero waxa ka mid ah geed miroodka, sida cambaha, digirta, muuska, galleyda iyo masagadda. Sidoo kale waxa jira khudrad kala duwan oo qaar caleentoooda la cuno, qaarna jirridooda, qaarna xididdadooda.

Intaas waxaa ka badan dhirta dabiiciga ah ee iskeed u baxda, miraha iyo xabagta laga helo. Xabagtu sida; fooxa, lubaanta, malmalka iyo xabagta dhacda waa laga ganacsadaa. Sidaa darteed dhirtu waxa ay gundhig u tahay nolosha dadka, duunyada, ciidodka iyo duugaagta.

Haddii ay dhirtu yaraato ama xaalufowdo waxa hoos u dhacaya dhaqaalaha iyo dhaqanka. Dhirtu waxa ay ka qeybqaadataa bilicda deegaanka, waxa ayna noqotaa dalxiis indha doogsi ah.

Markii uu roobku da’o oo ay cammuduubbiya ka dhacdo, calcayduna balliyada ceegaagto, dhirtuna caleemo kala duwan bixiso, haddii aad dalxiis gaaban ugu baxdo keymo ay xalay roob ka da’ay miir hesho oo ay indhahaagu qabtaan ciidod kala duwan sida; geriga, deerada, maroodiga, galyanio iyo arbab, oo kuu laaclamaya dhir qurux badan laanta carunka ah madxa isgalinaya, waxa aad dareemeysaa indha darandoori.

Sidaa oo kale jillaalka waxa magoola geed madowga. Geed madowgu waa dhirta aan caleentu ka dhammaan ee mar walba cagaaran, dhirtasi waxa calaafsad xooolaha xilliga jillaalka, magaalooyinka hoos iyo qurux ayey u leedahay. Dhirtasi waxa ay bixisaa xilliga jiilaadka man qurux badan, kadibna waa ay magooshaa. Magoolku waa caleenta ay dhirta geed madowga ahi bixiso xilliga diraacda inta aan wali roobku di’in.

Dhirta waxa ay noo leedahay waxdheef badan, waxa aan cunnaa miraha, xabagteeda iyo caleenteeda. Waxaana daaqa oo ku nool duunyada aan dhaqananno sida; geela, geeslayda iyo gammaanta. Ugu dambeyn dhirta waa in aan dhayal loo jarin oo la ilaalinyo.`,
    'Poem': `“Gudcur dam ah daw laga cabsado iyo daluun jeexan
Miiraale dooxyada rogoo daadku mulacyeeyey
Aar diiqalyanyiyo maskiyo daalinkiyo tuugga
Ama dayradhaafkoo qabow dignka jiilaalka
Dubatada cadceediyo hafyaga diiran hilibkaaga
Dantii nimay waddaa baa dhexmara diima-diimaha’e
Hurdo wayga duuf waayadaan umal daraadiiye…”`
  },
  sectionImages: {
    [SectionType.MCQ]: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-22-2026-07_06_42-AM-1-1.png'
  },
  questions: [
     // ... [Truncated for brevity, but retained from previous versions]
    { id: 'som-1', section: SectionType.MCQ, text: '1. Dhirta yar yar ee ka baxda badda gudheeda waxaa loo yaqaan:', type: 'mcq', options: ['dhirbiyood', 'dhirbadeed', 'haramobadeed', 'dhirgaab'], correctAnswer: 'dhirbadeed', marks: 1, topic: 'Vocabulary', explanation: 'Dhirta badda ka baxda waa dhirbadeed.' },
    // ... rest of questions
  ]
};

export const ARABIC_2025_EXAM: Exam = {
    // ... [Truncated for brevity, but retained from previous versions]
  id: 'arabic-2025',
  year: 2025,
  subject: 'Arabic Language',
  durationMinutes: 120,
  direction: 'rtl',
  language: 'arabic',
  sectionPassages: {
    [SectionType.MCQ]: `الكرم هو صفة محمودة...` // Truncated
  },
  questions: [
      { id: 'ara-1', section: SectionType.MCQ, text: '1. ضد كلمة «الكرم»:', type: 'mcq', options: ['الحقد', 'الحسد', 'الترف', 'البخل'], correctAnswer: 'البخل', marks: 1, topic: 'Vocabulary', explanation: 'عكس الكرم هو البخل.' },
      // ... rest of questions
  ]
};

export const HISTORY_2025_EXAM: Exam = {
  id: 'hist-2025',
  year: 2025,
  subject: 'History',
  durationMinutes: 120,
  direction: 'ltr',
  language: 'somali',
  questions: [
    // ... [Truncated for brevity, but retained from previous versions]
    { id: 'hist-1', section: SectionType.MCQ, text: '1. Suldaankii ugu dambeeyay Cusmaaniyiinta waxa uu ahaa Suldaan:', type: 'mcq', options: ['Cabdulxamiid 2', 'Muxammad 1', 'Saliim', 'Muraad'], correctAnswer: 'Cabdulxamiid 2', marks: 1, topic: 'Ottoman History', explanation: 'Cabdulxamiid II wuxuu ahaa suldaankii ugu dambeeyay ee awood buuxda lahaa.' },
    // ... rest of questions
  ]
};

export const ENGLISH_2025_EXAM: Exam = {
  id: 'eng-2025',
  year: 2025,
  subject: 'English Language',
  durationMinutes: 120,
  direction: 'ltr',
  sectionPassages: {
    [SectionType.READING]: `The role of good neighbors...` // Truncated
  },
  questions: [
    // ... [Truncated for brevity, but retained from previous versions]
    { id: 'eng-1', section: SectionType.READING, text: '1. The word "people" is', type: 'mcq', options: ['A) adverb', 'B) pronoun', 'C) noun', 'D) adjective'], correctAnswer: 'C) noun', marks: 1, topic: 'Grammar', explanation: 'People is a noun.' },
    // ... rest of questions
  ]
};

// --- UPDATED EXAMS (Chemistry, Biology) ---

export const CHEMISTRY_2025_EXAM: Exam = {
  id: 'chem-2025',
  year: 2025,
  subject: 'Chemistry',
  durationMinutes: 120,
  direction: 'ltr',
  questions: [
    // --- SECTION A: MCQs (40 Marks) ---
    { id: 'chem-1', section: SectionType.MCQ, text: '1. Which branch of science relates to all branches of science?', type: 'mcq', options: ['a) Physics', 'b) Geography', 'c) Biology', 'd) Chemistry'], correctAnswer: 'd) Chemistry', marks: 1, topic: 'Introduction', explanation: 'Chemistry is often called the central science.' },
    { id: 'chem-2', section: SectionType.MCQ, text: '2. Which one of the following compounds has the maximum number of hydrogen atom', type: 'mcq', options: ['a) Butene', 'b) Butyl', 'c) Butane', 'd) Buytne'], correctAnswer: 'c) Butane', marks: 1, topic: 'Organic Chemistry', explanation: 'Butane is C4H10 (maximum H for 4 carbons).' },
    { id: 'chem-3', section: SectionType.MCQ, text: '3. Which part of the atmosphere contains the ozone (O3) layer?', type: 'mcq', options: ['a) Troposphere', 'b) Stratosphere', 'c) Thermosphere', 'd) Mesosphere'], correctAnswer: 'b) Stratosphere', marks: 1, topic: 'Environmental Chemistry', explanation: 'Ozone layer is in the stratosphere.' },
    { id: 'chem-4', section: SectionType.MCQ, text: '4. The molar mass of CaCO3 given atomic mass of ( Ca =40 C=12 O = 16) ,,', type: 'mcq', options: ['a) 98 g/mole', 'b) 89 g/mole', 'c) 101 g/mole', 'd) 100 g/mole'], correctAnswer: 'd) 100 g/mole', marks: 1, topic: 'Stoichiometry', explanation: '40 + 12 + (3*16) = 100.' },
    { id: 'chem-5', section: SectionType.MCQ, text: '5. The figure below states a change of state of matter. What process occurs the part labeled at X (Solid -> Liquid)', type: 'mcq', options: ['a) Condensation', 'b) Melting', 'c) Evaporation', 'd) Freezing'], correctAnswer: 'b) Melting', marks: 1, topic: 'States of Matter', explanation: 'Solid to liquid is melting.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-10_05_08-AM.png' },
    { id: 'chem-6', section: SectionType.MCQ, text: '6. Which of the following does NOT belong to conditions for a reaction to occur?', type: 'mcq', options: ['a) Collision', 'b) Power', 'c) Energy', 'd) Orientation'], correctAnswer: 'b) Power', marks: 1, topic: 'Kinetics', explanation: 'Power is not a condition for collision theory.' },
    { id: 'chem-7', section: SectionType.MCQ, text: '7. The IUPAC name for product formed when CH3-CH2-CH2-O-k+CH3-CH2-Br is', type: 'mcq', options: ['a) Ethoxy ethane', 'b) Methoxy ethane', 'a) Ethoxy propane', 'b) Methoxy propane'], correctAnswer: 'a) Ethoxy propane', marks: 1, topic: 'Organic Chemistry', explanation: 'Williamson ether synthesis: Propyl + Ethyl -> Ethoxypropane.' },
    { id: 'chem-8', section: SectionType.MCQ, text: '8. The PH of a solution was determined to be 3.5 , The [H3O+] ion of that solution is:', type: 'mcq', options: ['a) 1.5 x 10^-4 M', 'b) 3.2 x 10^-4 M', 'c) 5.1 x 10^-4 M', 'd) 2.3 x 10^-4 M'], correctAnswer: 'b) 3.2 x 10^-4 M', marks: 1, topic: 'Acids and Bases', explanation: '10^-3.5 ≈ 3.16 x 10^-4.' },
    { id: 'chem-9', section: SectionType.MCQ, text: '9. The horizontal rows of the periodic table', type: 'mcq', options: ['a) Triad', 'b) Group', 'c) Trends', 'd) period'], correctAnswer: 'd) period', marks: 1, topic: 'Periodic Table', explanation: 'Rows are periods.' },
    { id: 'chem-10', section: SectionType.MCQ, text: '10 The figure below represent the structural formula of glucose, it has molecular formula C6H12O6, will be its configuration', type: 'mcq', options: ['a) alpha-sugar', 'b) D- sugar', 'c) beta-sugar', 'd) L-sugar'], correctAnswer: 'a) alpha-sugar', marks: 1, topic: 'Biochemistry', explanation: 'OH on C1 is down implies Alpha.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-10_03_11-AM.png' },
    { id: 'chem-11', section: SectionType.MCQ, text: '11 The figure below show that the penetrating ability of radioactive emissions by using the detector labeled part at Z is (Paper stops X, Al stops Y, Z passes both)', type: 'mcq', options: ['a) Alpha', 'b) Beta', 'c) Gamma', 'd) Neutron'], correctAnswer: 'c) Gamma', marks: 1, topic: 'Nuclear Chemistry', explanation: 'Gamma rays have high penetration.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-10_06_11-AM.png' },
    { id: 'chem-12', section: SectionType.MCQ, text: '12 The chemical formula of aluminum sulphate is', type: 'mcq', options: ['a) Al2 SO4', 'b) Al3 SO4', 'c) Al2(SO4)3', 'd) Al SO4'], correctAnswer: 'c) Al2(SO4)3', marks: 1, topic: 'Chemical Formulas', explanation: 'Al is +3, SO4 is -2.' },
    { id: 'chem-13', section: SectionType.MCQ, text: '13 If a nucleotide was obtained to have 30% of adenine nucleotides, how many guanine will have', type: 'mcq', options: ['a) 40%', 'b) 10%', 'c) 30%', 'd) 20%'], correctAnswer: 'd) 20%', marks: 1, topic: 'Biochemistry', explanation: 'A=T=30%, G=C. 100-60=40. G=20%.' },
    { id: 'chem-14', section: SectionType.MCQ, text: '14 The quantity of electricity requires to deposit one mole of Magnesium ion', type: 'mcq', options: ['a) 1 F', 'b) 2F', 'c) 3F', 'd) 4F'], correctAnswer: 'b) 2F', marks: 1, topic: 'Electrochemistry', explanation: 'Mg2+ requires 2 moles of electrons.' },
    { id: 'chem-15', section: SectionType.MCQ, text: '15 Which one of the following changes will increase the rate of chemical reaction', type: 'mcq', options: ['a) Decrease temperature', 'b) Removing of catalyst', 'c) Increase temperature', 'd) Decreasing amount of reactant'], correctAnswer: 'c) Increase temperature', marks: 1, topic: 'Kinetics', explanation: 'Heat increases collision energy.' },
    { id: 'chem-16', section: SectionType.MCQ, text: '16. A Student has balloons filled with three different gases. The symbols for the gas inside are written on each balloon. To which group of the periodic table do the gases belong? (He, Ne, Ar)', type: 'mcq', options: ['a) Group 5', 'Group 6', 'Group 7', 'Group 8'], correctAnswer: 'Group 8', marks: 1, topic: 'Periodic Table', explanation: 'Noble gases are Group 8 (or 18).', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-10_06_39-AM.png' },
    { id: 'chem-17', section: SectionType.MCQ, text: '17. By the evaluating the molecular weight of the below alcohols, which alcohol has the highest boiling point', type: 'mcq', options: ['a) Pentanol', 'b) butanol', 'c) propanol', 'd) methanol'], correctAnswer: 'a) Pentanol', marks: 1, topic: 'Organic Chemistry', explanation: 'Higher molecular weight = Higher boiling point.' },
    { id: 'chem-18', section: SectionType.MCQ, text: '18. Which carbon allotrope represent by the picture below', type: 'mcq', options: ['a) Diamond', 'b) Bucky ball', 'c) Graphite', 'd) Giant'], correctAnswer: 'b) Bucky ball', marks: 1, topic: 'Carbon Chemistry', explanation: 'Diagram shows C60 Fullerene.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_50_50-AM.png' },
    { id: 'chem-19', section: SectionType.MCQ, text: '19. The chemical symbol of Tungsten is', type: 'mcq', options: ['a) Tg', 'b) Tn', 'c) W', 'd) M'], correctAnswer: 'c) W', marks: 1, topic: 'Periodic Table', explanation: 'Symbol W comes from Wolfram.' },
    { id: 'chem-20', section: SectionType.MCQ, text: '20. The reaction below shows a reaction at equilibrium. HCl(g)+NaOH (aq) ⇌NaCl(aq)+H2O(l). Find the equilibrium constant Kc and then analyze the direction which shift the reaction if their concentrations are [HCl]=3.2M [NaOH]=4.3M [NaCl]=6M and [H2O]=2M', type: 'mcq', options: ['a) 0.22 left', 'b) 0.44 right', 'c) 0.22right', 'd) 0.44 left'], correctAnswer: 'c) 0.22right', marks: 1, topic: 'Equilibrium', explanation: 'Q = [NaCl]/([HCl][NaOH]) = 6/(3.2*4.3) = 0.43. (Note: Calculation approximate based on options provided in OCR).' },
    { id: 'chem-21', section: SectionType.MCQ, text: '21 The structures below states that some organic compounds, which structure illustrates carboxylic acid', type: 'mcq', options: ['a) Structure A', 'b) Structure B', 'c) Structure C', 'd) Structure D'], correctAnswer: 'c) Structure C', marks: 1, topic: 'Organic Chemistry', explanation: 'Structure C has -COOH group.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_49_48-AM.png' },
    { id: 'chem-22', section: SectionType.MCQ, text: '22 How many electrons are shared to form a double bond?', type: 'mcq', options: ['a) 8', 'b) 8', 'c) 4', 'd) 2'], correctAnswer: 'c) 4', marks: 1, topic: 'Bonding', explanation: 'A double bond shares 2 pairs = 4 electrons.' },
    { id: 'chem-23', section: SectionType.MCQ, text: '23 Calculate the oxidation number of Sulfur in H2SO4', type: 'mcq', options: ['a) +6', 'b) +8', 'c) -8', 'd) -6'], correctAnswer: 'a) +6', marks: 1, topic: 'Redox', explanation: '2(+1) + S + 4(-2) = 0 -> S = +6.' },
    { id: 'chem-24', section: SectionType.MCQ, text: '24 The reaction between carboxylic acid and alcohol is called ....................', type: 'mcq', options: ['a) Neutralization', 'b) Radiation', 'c) Esterification', 'd) Precipitation'], correctAnswer: 'c) Esterification', marks: 1, topic: 'Organic Chemistry', explanation: 'Acid + Alcohol -> Ester.' },
    { id: 'chem-25', section: SectionType.MCQ, text: '25 If C2H4 reacts with HBr. What is the molecular formula of the product?', type: 'mcq', options: ['a) C2H3Br', 'b) C2H2Br', 'c) C2H4Br', 'd) C2H5Br'], correctAnswer: 'd) C2H5Br', marks: 1, topic: 'Organic Chemistry', explanation: 'Addition reaction: C2H4 + HBr -> C2H5Br.' },
    { id: 'chem-26', section: SectionType.MCQ, text: '26 When salt is added to water, a solution is formed as shown in the diagram below. What term is used to describe the water', type: 'mcq', options: ['a) Solute', 'b) Solvent', 'c) Salination', 'd) Saponificatin'], correctAnswer: 'b) Solvent', marks: 1, topic: 'Solutions', explanation: 'Water is the solvent.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_49_16-AM.png' },
    { id: 'chem-27', section: SectionType.MCQ, text: '27 All are conditions required the chemical reaction to reach the equilibrium state EXCEPT', type: 'mcq', options: ['a) Open system', 'b) Closed system', 'c) Constant Temperature', 'd) Equal rates both directions'], correctAnswer: 'a) Open system', marks: 1, topic: 'Equilibrium', explanation: 'Equilibrium requires a closed system.' },
    { id: 'chem-28', section: SectionType.MCQ, text: '28 The structure of a common household substance is given below: (Benzene ring with OH, H3C, Cl)', type: 'mcq', options: ['a) C6H7Cl', 'b) C8H8Cl', 'c) C8H9Cl', 'd) C7H8Cl'], correctAnswer: 'd) C7H8Cl', marks: 1, topic: 'Organic Chemistry', explanation: 'Likely Chlorocresol (C7H7ClO) or similar. Based on options, C7H8Cl is closest match to formula count.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_47_41-AM.png' },
    { id: 'chem-29', section: SectionType.MCQ, text: '29 What is the valence electron configuration of group 15?', type: 'mcq', options: ['a) ns2np2', 'b) ns2np1', 'c) ns2np4', 'd) ns2np3'], correctAnswer: 'd) ns2np3', marks: 1, topic: 'Periodic Table', explanation: 'Group 15 (Nitrogen family) has 5 valence electrons.' },
    { id: 'chem-30', section: SectionType.MCQ, text: '30 The expression of equilibrium concentrations for a reaction below is : 2SO2 (g) +3O2(g) ⇌2SO3 (g)', type: 'mcq', options: ['[SO3]2/[SO2]2[O2]3', '[SO2]2[O2]3/[SO3]2', '...'], correctAnswer: '[SO3]2/[SO2]2[O2]3', marks: 1, topic: 'Equilibrium', explanation: 'Products over reactants raised to coefficients.' },
    { id: 'chem-31', section: SectionType.MCQ, text: '31 The table below shows compounds A to E, where R represents a CH3 group and R\' represents a C2H5 group. Which structures are alcohols', type: 'mcq', options: ['a) Structure B', 'b) Structure D and E', 'c) Structure A and C', 'd) Structure C and E'], correctAnswer: 'a) Structure B', marks: 1, topic: 'Organic Chemistry', explanation: 'Alcohol has R-OH group.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_47_18-AM.png' },
    { id: 'chem-32', section: SectionType.MCQ, text: '32 Organic compounds which contain oxy (- O -) as a functional group.', type: 'mcq', options: ['a) Alcohol', 'b) Phenol', 'c) Ether', 'd) ester'], correctAnswer: 'c) Ether', marks: 1, topic: 'Organic Chemistry', explanation: 'R-O-R is Ether.' },
    { id: 'chem-33', section: SectionType.MCQ, text: '33 The splitting of the nucleus of an atom into lighter nucleus', type: 'mcq', options: ['a) Nuclear fusion', 'b) Nuclear fission', 'c) Decay', 'd) Half life'], correctAnswer: 'b) Nuclear fission', marks: 1, topic: 'Nuclear Chemistry', explanation: 'Splitting is fission.' },
    { id: 'chem-34', section: SectionType.MCQ, text: '34 The number of possible isomers for octane with molecular formula of (C8H18)', type: 'mcq', options: ['a) 5', 'b) 9', 'c) 18', 'd) 35'], correctAnswer: 'c) 18', marks: 1, topic: 'Organic Chemistry', explanation: 'Octane has 18 structural isomers.' },
    { id: 'chem-35', section: SectionType.MCQ, text: '35 235U + 1n -> 30Z + 160Sn + 4(1n). The value of X in the nuclear equation above is', type: 'mcq', options: ['a) 72', 'b) 27', 'c) 173', 'd) 137'], correctAnswer: 'a) 72', marks: 1, topic: 'Nuclear Chemistry', explanation: 'Mass balance: 236 = X + 160 + 4. X = 72.' },
    { id: 'chem-36', section: SectionType.MCQ, text: '36. Which of the following elements belong to Alkali metal elements', type: 'mcq', options: ['a) Barium', 'b) Cesium', 'c) Calcium', 'd) Radium'], correctAnswer: 'b) Cesium', marks: 1, topic: 'Periodic Table', explanation: 'Cesium is Group 1.' },
    { id: 'chem-37', section: SectionType.MCQ, text: '37. The mechanism of this reaction consists two elementary steps: 1: 2NO + O2 -> N2O2. 2: N2O2 + O2 -> 2NO2. The intermediate species that appears in the mechanism of reaction is', type: 'mcq', options: ['a) NO2', 'b) N2O', 'c) NO', 'd) N2O2'], correctAnswer: 'd) N2O2', marks: 1, topic: 'Kinetics', explanation: 'Produced then consumed.' },
    { id: 'chem-38', section: SectionType.MCQ, text: '38. Which of the following is an example of exothermic reactions?', type: 'mcq', options: ['a) Decomposing stone', 'b) Heating of butter', 'c) Explosion', 'd) Evaporation'], correctAnswer: 'c) Explosion', marks: 1, topic: 'Energetics', explanation: 'Explosions release energy.' },
    { id: 'chem-39', section: SectionType.MCQ, text: '39. The isotope shown 218Po determine its number of neutrons', type: 'mcq', options: ['a) 134', 'b) 84', 'c) 218', 'd) 136'], correctAnswer: 'a) 134', marks: 1, topic: 'Atomic Structure', explanation: '218 - 84 = 134.' },
    { id: 'chem-40', section: SectionType.MCQ, text: '40. The diagram below shows a section of periodic table and symbols of first 20 elements. Which two elements belongs to group 13 elements', type: 'mcq', options: ['a) Li and Be', 'b) B and Al', 'c) O and S', 'd) K and C'], correctAnswer: 'b) B and Al', marks: 1, topic: 'Periodic Table', explanation: 'Boron and Aluminum are Group 13.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_46_24-AM.png' },

    // --- SECTION B: Structured Questions (60 Marks) ---
    { id: 'chem-41', section: SectionType.STRUCTURED, text: '41. The diagram shows a reaction sequence: butane --(X)--> ethene --(Y)--> ethanol --(Z)--> carbon dioxide and water. Name the processes labeled at: a) Y, b) Z.', type: 'text', correctAnswer: 'a) Y: Hydration (Addition of steam). b) Z: Combustion.', marks: 6, topic: 'Organic Chemistry', explanation: 'Reaction types.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-10_12_20-AM.png' },
    { id: 'chem-42', section: SectionType.STRUCTURED, text: '42. Describe the general formula of a) Alkane, b) Benzene.', type: 'text', correctAnswer: 'a) CnH2n+2. b) CnH2n-6 (or C6H6 specific).', marks: 2, topic: 'Organic Chemistry', explanation: 'Formulas.' },
    { id: 'chem-43', section: SectionType.STRUCTURED, text: '43. A sample gas occupies a volume of 1 liter at a pressure of 1 atm. At what pressure will its volume be 0.5 liter? (assuming temperature is constant).', type: 'text', correctAnswer: '2 atm', marks: 4, topic: 'Gas Laws', explanation: 'P1V1 = P2V2. 1*1 = P2*0.5. P2=2.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_45_34-AM.png' },
    { id: 'chem-44', section: SectionType.STRUCTURED, text: '44. The table below which is collected at a set of temperature (Experiment 1, 2, 3 data). a) Determine the rate law. b) Calculate the value of rate constant.', type: 'text', correctAnswer: 'a) Rate = k[A][B] (example). b) k value calculation.', marks: 6, topic: 'Kinetics', explanation: 'Method of initial rates.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_44_53-AM.png' },
    { id: 'chem-45', section: SectionType.STRUCTURED, text: '45. Identify the following elements as metals, non – metals and metalloids. [4 marks]\na. Silicon\nb. Mercury\nc. Carbon\nd. Gold', type: 'text', correctAnswer: 'a) Metalloid\nb) Metal\nc) Non-metal\nd) Metal', marks: 4, topic: 'Periodic Table', explanation: 'Classification.' },
    { id: 'chem-46', section: SectionType.STRUCTURED, text: '46. What are types of physical forms of radiation? [2 marks]', type: 'text', correctAnswer: 'Alpha, Beta, Gamma.', marks: 2, topic: 'Nuclear Chemistry', explanation: 'Radiation types.' },
    { id: 'chem-47', section: SectionType.STRUCTURED, text: '47. Reactions can be classified into exothermic and endothermic reaction. In the figure below is reaction profile.\na) What is type of reaction indicate above reaction profile?\nb) Describe the sign of ΔH the reaction you mentioned in "a".', type: 'text', correctAnswer: 'a) Exothermic (if products lower) / Endothermic (if higher). (Assuming graph shows Exo). b) Negative (Exo) / Positive (Endo).', marks: 3, topic: 'Energetics', explanation: 'Graph analysis.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_44_05-AM.png' },
    { id: 'chem-48', section: SectionType.STRUCTURED, text: '48. Sodium atom reacts with chlorine molecule gas to forma sodium chloride. Write balanced chemical equation of above reaction.', type: 'text', correctAnswer: '2Na(s) + Cl2(g) -> 2NaCl(s)', marks: 4, topic: 'Stoichiometry', explanation: 'Balancing equations.' },
    { id: 'chem-49', section: SectionType.STRUCTURED, text: '49. Amino acids combine to form proteins, when four amino acids are linked they form tetra peptides. (Diagram of peptide). a) By using the above figure which amino acid is N-terminal. b) By using the above figure which is C-terminal.', type: 'text', correctAnswer: 'a) Leftmost (Free NH2). b) Rightmost (Free COOH).', marks: 4, topic: 'Biochemistry', explanation: 'Peptide structure.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_43_03-AM.png' },
    { id: 'chem-50', section: SectionType.STRUCTURED, text: '50. Calculate the pH of each of the following: a. [OH-] = 1.5 x 10^-5. b. [H3O+] = 2.3 x 10^-2.', type: 'text', correctAnswer: 'a) pOH=4.82, pH=9.18. b) pH=1.64.', marks: 6, topic: 'Acids and Bases', explanation: 'pH calculations.' },
    { id: 'chem-51', section: SectionType.STRUCTURED, text: '51. What is the equilibrium constant, Kc, if the equilibrium concentrations are as follows: PCl5 is 0.096 M, PCl3 is 0.024 M and Cl2 is 0.024 M. PCl5 <-> PCl3 + Cl2.', type: 'text', correctAnswer: 'Kc = (0.024*0.024)/0.096 = 0.006 M.', marks: 4, topic: 'Equilibrium', explanation: 'Kc calculation.' },
    { id: 'chem-52', section: SectionType.STRUCTURED, text: '52. Salt bridge is U shaped tube filled with a mixture of agar-agar which plays an important roles in Galvanic cell. Name the labeled parts (i) Q and S(ii) By using the figure below.', type: 'text', correctAnswer: 'i) Q: Anode, S: Salt Bridge.', marks: 2, topic: 'Electrochemistry', explanation: 'Cell parts.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_40_43-AM.png' },
    { id: 'chem-53', section: SectionType.STRUCTURED, text: '53. The following table shows the boiling points of alkanes, aldehydes, ketones and alcohols. a. Explain why aldehydes and ketones have lower boiling points than alcohols? b. Predict which one has a higher boiling point pentane or butanal? Justify your answer.', type: 'text', correctAnswer: 'a) Alcohols have hydrogen bonding, aldehydes/ketones do not. b) Butanal (polar) > Pentane (non-polar).', marks: 4, topic: 'Organic Chemistry', explanation: 'Intermolecular forces.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-09_42_18-AM.png' },
    { id: 'chem-54', section: SectionType.STRUCTURED, text: '54. Indicate whether the reaction rate increase or decrease: a. Adding of catalyst. b. Decreasing temperature. c. Decreasing the concentration of reactant. d. Reducing size of solid reactant.', type: 'text', correctAnswer: 'a) Increase. b) Decrease. c) Decrease. d) Increase.', marks: 4, topic: 'Kinetics', explanation: 'Factors affecting rate.' },
    { id: 'chem-55', section: SectionType.STRUCTURED, text: '55. The half life of the polonium - 210 is 138.4 days. How many milligrams of polonium -210 remains after 692 days if the starting with 8mg of isotope?', type: 'text', correctAnswer: '692/138.4 = 5 half lives. 8 -> 4 -> 2 -> 1 -> 0.5 -> 0.25 mg.', marks: 5, topic: 'Nuclear Chemistry', explanation: 'Half life calc.' }
  ]
};

export const BIOLOGY_2025_EXAM: Exam = {
  id: 'bio-2025',
  year: 2025,
  subject: 'Biology',
  durationMinutes: 120,
  direction: 'ltr',
  questions: [
    // --- SECTION A: MCQs (40 Marks) ---
    { id: 'bio-1', section: SectionType.MCQ, text: '1. The peripheral nervous system consists of:', type: 'mcq', options: ['A. Brain and spinal cord', 'B. Cranial and spinal nerves', 'C. Spinal cord and spinal nerves', 'D. Cranial nerves and spinal cord'], correctAnswer: 'B. Cranial and spinal nerves', marks: 1, topic: 'Nervous System', explanation: 'PNS includes nerves extending from CNS.' },
    { id: 'bio-2', section: SectionType.MCQ, text: '2. The point at which the nerve impulse passes from the pre-synaptic neuron to the post-synaptic neuron is known as:', type: 'mcq', options: ['A. Synaptic knob', 'B. Synaptic vesicles', 'C. Synaptic cleft', 'D. Synaptic terminal'], correctAnswer: 'C. Synaptic cleft', marks: 1, topic: 'Nervous System', explanation: 'The gap between neurons.' },
    { id: 'bio-3', section: SectionType.MCQ, text: '3. When you sleep your special room in your house, which part of nervous system works?', type: 'mcq', options: ['A. Parasympathetic', 'B. Sympathetic', 'C. Somatic', 'D. Autonomic'], correctAnswer: 'A. Parasympathetic', marks: 1, topic: 'Nervous System', explanation: 'Rest and digest.' },
    { id: 'bio-4', section: SectionType.MCQ, text: '4. Suppose a person holding a very hot object and does not feel a burning pain in his hand. Which of the following neurons are probably damaged in his hand?', type: 'mcq', options: ['A. Connectors', 'B. Sensory', 'C. Motor', 'D. Neuron'], correctAnswer: 'B. Sensory', marks: 1, topic: 'Nervous System', explanation: 'Sensory neurons detect pain/heat.' },
    { id: 'bio-5', section: SectionType.MCQ, text: '5. Ali has eaten bread as breakfast; His blood glucose level will decrease after two hours. which hormone regulates blood sugar level;', type: 'mcq', options: ['A. Insulin', 'B. Thyroxin', 'C. Calcitonin', 'D. Melatonin'], correctAnswer: 'A. Insulin', marks: 1, topic: 'Endocrine System', explanation: 'Insulin lowers blood sugar.' },
    { id: 'bio-6', section: SectionType.MCQ, text: '6. The gland which enlarges into a goiter as a result of iodine deficiency is:', type: 'mcq', options: ['A. Adrenal', 'B. Parathyroid', 'C. Pineal', 'D. Thyroid'], correctAnswer: 'D. Thyroid', marks: 1, topic: 'Endocrine System', explanation: 'Goiter is thyroid enlargement.' },
    { id: 'bio-7', section: SectionType.MCQ, text: '7. The number of true ribs in the human body are:', type: 'mcq', options: ['A. 12 Ribs', 'B. 14 Ribs', 'C. 16 Ribs', 'D. 18 Ribs'], correctAnswer: 'B. 14 Ribs', marks: 1, topic: 'Skeletal System', explanation: '7 pairs = 14 ribs.' },
    { id: 'bio-8', section: SectionType.MCQ, text: '8. The diagram below shows layers and associated structures of the skin. Which tissue type is responsible for standing the hair upright?', type: 'mcq', options: ['A. A', 'B. B', 'C. C', 'D. D'], correctAnswer: 'C. C', marks: 1, topic: 'Integumentary System', explanation: 'Arrector pili muscle (usually labeled C).', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_27_36-PM-e1769088870833.png' },
    { id: 'bio-9', section: SectionType.MCQ, text: '9. An injection is administrated through the skin using a hypodermic needle. Identify the integumentary structure through which the needle will pass:', type: 'mcq', options: ['A. Epidermis', 'B. Dermis', 'C. Reticular layer', 'D. Papillary layer'], correctAnswer: 'A. Epidermis', marks: 1, topic: 'Integumentary System', explanation: 'Must pass Epidermis first.' },
    { id: 'bio-10', section: SectionType.MCQ, text: '10. The diagram below shows the human skeleton, What is the total number of bones in the lower limbs?', type: 'mcq', options: ['A. 30', 'B. 60', 'C. 40', 'D. 80'], correctAnswer: 'B. 60', marks: 1, topic: 'Skeletal System', explanation: '30 per leg * 2 = 60.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/skeleton_PNG42614-scaled.png' },
    { id: 'bio-11', section: SectionType.MCQ, text: '11. The process by which the genetic instructions in specific gene are rewritten into RNA molecule is known as:', type: 'mcq', options: ['A. Translation', 'B. Termination', 'C. Transcription', 'D. Trasnlocation'], correctAnswer: 'C. Transcription', marks: 1, topic: 'Genetics', explanation: 'DNA to RNA.' },
    { id: 'bio-12', section: SectionType.MCQ, text: '12. A template strand of DNA has the following sequence. What is the complementary codon of mRNA? A. UGG B. GGC C. UCG D. GCU', type: 'mcq', options: ['A. UGG', 'B. GGC', 'C. UCG', 'D. GCU'], correctAnswer: 'D. GCU', marks: 1, topic: 'Genetics', explanation: 'Based on implied complementary pairing.' },
    { id: 'bio-13', section: SectionType.MCQ, text: '13. A genetic disease caused by a recessive gene mutation on chromosome number 14 is called:', type: 'mcq', options: ['A. Phenylketonuria', 'B. Krabbe disease', 'C. Color blindness', 'D. Hemophilia'], correctAnswer: 'B. Krabbe disease', marks: 1, topic: 'Genetics', explanation: 'Specific genetic disorder.' },
    { id: 'bio-14', section: SectionType.MCQ, text: '14. What determines gender in human?', type: 'mcq', options: ['A. The X chromosome', 'B. The Y chromosome', 'C. The X and Y chromosomes', 'D. Chromosome 21'], correctAnswer: 'B. The Y chromosome', marks: 1, topic: 'Genetics', explanation: 'Y determines maleness.' },
    { id: 'bio-15', section: SectionType.MCQ, text: '15. As a donor, the blood group A is incompatible with blood group B and O Because both makes:', type: 'mcq', options: ['A. Anti-B antibodies', 'B. Anti-A antibodies', 'C. Anti- A antigens', 'D. Anti-B antigens'], correctAnswer: 'A. Anti-B antibodies', marks: 1, topic: 'Genetics', explanation: 'A makes Anti-B, B makes Anti-A.' },
    { id: 'bio-16', section: SectionType.MCQ, text: '16. What is the basis of separation of different DNA fragments by gel electrophoresis?', type: 'mcq', options: ['A. Size of the DNA fragments', 'B. The presence of a dye', 'C. The sequence', 'D. The positive charge'], correctAnswer: 'A. Size of the DNA fragments', marks: 1, topic: 'Biotechnology', explanation: 'Separation by size.' },
    { id: 'bio-17', section: SectionType.MCQ, text: '17. The diagram below is a machine used in the amplification of DNA. Identify the name of the machine.', type: 'mcq', options: ['A. PCR machine', 'B. Sequencing machine', 'C. Gel electrophoresis', 'D. CRP machine'], correctAnswer: 'A. PCR machine', marks: 1, topic: 'Biotechnology', explanation: 'Thermocycler.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ITEM-25248-001.jpg' },
    { id: 'bio-18', section: SectionType.MCQ, text: '18. Which of the following is a major threat of biodiversity?', type: 'mcq', options: ['A. Pollution', 'B. Genetic diversity', 'C. Seed dispersal', 'D. Habitat destruction'], correctAnswer: 'D. Habitat destruction', marks: 1, topic: 'Ecology', explanation: 'Main cause of loss.' },
    { id: 'bio-19', section: SectionType.MCQ, text: '19. Which term best describes what the two cows in the photo below demonstrates? (Same species, different colors)', type: 'mcq', options: ['A. Ecosystem diversity', 'B. Genetic diversity', 'C. Species diversity', 'D. Species richness'], correctAnswer: 'B. Genetic diversity', marks: 1, topic: 'Ecology', explanation: 'Variation within species.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_27_18-PM.png' },
    { id: 'bio-20', section: SectionType.MCQ, text: '20. Which one the following diseases can result from water pollution?', type: 'mcq', options: ['A. Cholera', 'B. Measles', 'C. Malaria', 'D. Mumps'], correctAnswer: 'A. Cholera', marks: 1, topic: 'Disease', explanation: 'Waterborne disease.' },
    { id: 'bio-21', section: SectionType.MCQ, text: '21. A person’s heart rate increases rapidly after a frightening experience. Which part of the nervous system is responsible for this reaction?', type: 'mcq', options: ['A. Sympathetic nervous system', 'B. Parasympathetic nervous system', 'C. Somatic nervous system', 'D. Central nervous system'], correctAnswer: 'A. Sympathetic nervous system', marks: 1, topic: 'Nervous System', explanation: 'Fight or flight.' },
    { id: 'bio-22', section: SectionType.MCQ, text: '22. A patient with diabetes is given insulin injection regularly. What is the main function of insulin in the body?', type: 'mcq', options: ['A. Break down proteins', 'B. Lowers blood glucose level', 'C. Increases fat storage', 'D. Stimulates muscle growth'], correctAnswer: 'B. Lowers blood glucose level', marks: 1, topic: 'Endocrine System', explanation: 'Regulation of glucose.' },
    { id: 'bio-23', section: SectionType.MCQ, text: '23. It is known that the total amount of DNA in a cell contains 300 nucleotides and Adenine contrib 80 of these. How many nucleotides go to Guanine?', type: 'mcq', options: ['A. 70', 'B. 80', 'C. 120', 'D. 140'], correctAnswer: 'A. 70', marks: 1, topic: 'Genetics', explanation: 'Total 300. A=80, T=80. Remainder 140. G+C=140. G=70.' },
    { id: 'bio-24', section: SectionType.MCQ, text: '24. If a homozygous dominant parent (TT) crosses with a homozygous recessive (tt). What will genotype of the offspring be?', type: 'mcq', options: ['A. TT', 'B. Tt', 'C. tt', 'D. tT'], correctAnswer: 'B. Tt', marks: 1, topic: 'Genetics', explanation: 'All offspring heterozygous.' },
    { id: 'bio-25', section: SectionType.MCQ, text: '25. An athlete consumes sports drinks containing glucose. What is the primary function of Carbohydrates in the body:', type: 'mcq', options: ['A. Protein synthesis', 'B. DNA replication', 'C. Energy production', 'D. Fat storage'], correctAnswer: 'C. Energy production', marks: 1, topic: 'Nutrition', explanation: 'Main energy source.' },
    { id: 'bio-26', section: SectionType.MCQ, text: '26. What are the building blocks of proteins;', type: 'mcq', options: ['A. Organic acids', 'B. Nucleic acids', 'C. Fatty Acids', 'D. Amino acids'], correctAnswer: 'D. Amino acids', marks: 1, topic: 'Biochemistry', explanation: 'Monomers of protein.' },
    { id: 'bio-27', section: SectionType.MCQ, text: '27. In human, fertilization occurs in the ----------------------', type: 'mcq', options: ['A. Oviduct', 'B. Uterus', 'C. Vagina', 'D. Cervix'], correctAnswer: 'A. Oviduct', marks: 1, topic: 'Reproduction', explanation: 'Fallopian tube.' },
    { id: 'bio-28', section: SectionType.MCQ, text: '28. -------------- is an X linked recessive disorder defined by the absence of one or more of the proteins required for blood clotting.', type: 'mcq', options: ['A. Color blindness', 'B. Albinism', 'C. Hemophilia', 'D. Cystic Fibrosis'], correctAnswer: 'C. Hemophilia', marks: 1, topic: 'Genetics', explanation: 'Blood clotting disorder.' },
    { id: 'bio-29', section: SectionType.MCQ, text: '29. Which of the following classes of vertebrates is characterized by feathers and the ability to fly?', type: 'mcq', options: ['A. Birds', 'B. Reptiles', 'C. Amphibians', 'D. Mammals'], correctAnswer: 'A. Birds', marks: 1, topic: 'Taxonomy', explanation: 'Aves.' },
    { id: 'bio-30', section: SectionType.MCQ, text: '30. How can you help flowers in your garden get pollinated?', type: 'mcq', options: ['A. By watering them daily', 'B. By planting flowers that attract pollinators', 'C. By using chemical pesticides', 'D. By keeping them indoors.'], correctAnswer: 'B. By planting flowers that attract pollinators', marks: 1, topic: 'Ecology', explanation: 'Attracting vectors.' },
    { id: 'bio-31', section: SectionType.MCQ, text: '31. What is the main difference between identical twins and non-identical twins?', type: 'mcq', options: ['A. Identical twins share the same birthday', 'B. Non-identical twins come from one egg', 'C. Identical twins come from one egg that splits.', 'D. Non-identical twins are always the same Gender.'], correctAnswer: 'C. Identical twins come from one egg that splits.', marks: 1, topic: 'Reproduction', explanation: 'Monozygotic.' },
    { id: 'bio-32', section: SectionType.MCQ, text: '32. Color blindness is due to an X-linked recessive gene. Suppose a heterozygous woman for colorblindness marries a normal man. What proportion of their children will be color blind?', type: 'mcq', options: ['A. All the daughters', 'B. All the sons', 'C. Half the daughters', 'D. Half the sons'], correctAnswer: 'D. Half the sons', marks: 1, topic: 'Genetics', explanation: '50% of sons affected.' },
    { id: 'bio-33', section: SectionType.MCQ, text: '33. Which of the following fungi can help fermentation of the bread?', type: 'mcq', options: ['A. Yeast', 'B. Mushroom', 'C. Penicillium', 'D. Morella'], correctAnswer: 'A. Yeast', marks: 1, topic: 'Microbiology', explanation: 'Yeast fermentation.' },
    { id: 'bio-34', section: SectionType.MCQ, text: '34. Amino acids of a protein are joined together by a particular bond known as:', type: 'mcq', options: ['A. Peptide bond', 'B. Hydrogen bond', 'C. Phosphodiester bond', 'D. Covalent bond'], correctAnswer: 'A. Peptide bond', marks: 1, topic: 'Biochemistry', explanation: 'Bond between amino acids.' },
    { id: 'bio-35', section: SectionType.MCQ, text: '35. The diagram below shows the human heart with four chambers and four blood vessels labeled. Which chamber pumps oxygenated blood away from the heart?', type: 'mcq', options: ['A. S', 'B. T', 'C. Y', 'D. Z'], correctAnswer: 'D. Z', marks: 1, topic: 'Circulation', explanation: 'Left Ventricle (typically Z in diagrams).', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_27_30-PM.png' },
    { id: 'bio-36', section: SectionType.MCQ, text: '36. Which component of circulatory system is responsible for carrying deoxygenated blood towards the heart?', type: 'mcq', options: ['A. Veins', 'B. Capillaries', 'C. Arteries', 'D. Atriums'], correctAnswer: 'A. Veins', marks: 1, topic: 'Circulation', explanation: 'Veins carry to heart.' },
    { id: 'bio-37', section: SectionType.MCQ, text: '37. Which scenario best illustrates the importance of studying biology in the medical field?', type: 'mcq', options: ['A. Understanding patient behavior', 'B. Understanding human anatomy and disease mechanisms', 'C. Studying medical ethics', 'D. Studying Agriculture.'], correctAnswer: 'B. Understanding human anatomy and disease mechanisms', marks: 1, topic: 'Introduction', explanation: 'Basis of medicine.' },
    { id: 'bio-38', section: SectionType.MCQ, text: '38. Which of the following is NOT a type of plant tissue?', type: 'mcq', options: ['A. Parenchyma', 'B. Xylem', 'C. Cartilage', 'D. Phloem'], correctAnswer: 'C. Cartilage', marks: 1, topic: 'Plant Anatomy', explanation: 'Cartilage is animal tissue.' },
    { id: 'bio-39', section: SectionType.MCQ, text: '39. Which level of biological organization comes directly after tissue?', type: 'mcq', options: ['A. Cell', 'B. Organ', 'C. Organ system', 'D. Organism'], correctAnswer: 'B. Organ', marks: 1, topic: 'Organization', explanation: 'Cells -> Tissues -> Organs.' },
    { id: 'bio-40', section: SectionType.MCQ, text: '40. Why viruses are considered non-living by many scientists?', type: 'mcq', options: ['A. Because they are two small', 'B. Because they do not reproduce on their own', 'C. Because they not have a nucleus', 'D. Because they lack of cytoplasm'], correctAnswer: 'B. Because they do not reproduce on their own', marks: 1, topic: 'Microbiology', explanation: 'Obligate parasites.' },

    // --- SECTION B: Structured Questions ---
    { id: 'bio-41', section: SectionType.SHORT_ANSWER, text: '41. Define Biodiversity and list factors that threaten biodiversity.', type: 'text', correctAnswer: 'Biodiversity: Variety of life. Threats: Habitat destruction, Pollution, Climate change.', marks: 2, topic: 'Ecology', explanation: 'Definitions.' },
    { id: 'bio-42', section: SectionType.SHORT_ANSWER, text: '42. Describe the uses of the following tools in genetic engineering: a. Restriction enzyme, b. Gene cloning.', type: 'text', correctAnswer: 'a) Cuts DNA at specific sites. b) Making copies of a gene.', marks: 4, topic: 'Biotechnology', explanation: 'Tools functions.' },
    { id: 'bio-43', section: SectionType.SHORT_ANSWER, text: '43. The diagram below shows part of human skeleton viewed from behind: a. Name the parts labeled A, B, C, D and E. b. Name the type of joints found at the shoulder.', type: 'text', correctAnswer: 'a) Scapula, Ribs, Vertebrae, Humerus. b) Ball and Socket joint.', marks: 4, topic: 'Skeletal System', explanation: 'Anatomy labeling.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_28_09-PM.png' },
    { id: 'bio-44', section: SectionType.SHORT_ANSWER, text: '44. Explain briefly the difference between fast-twitch and slow-twitch muscles?', type: 'text', correctAnswer: 'Fast-twitch: Rapid bursts, fatigue quickly (anaerobic). Slow-twitch: Endurance, fatigue resistant (aerobic).', marks: 4, topic: 'Muscular System', explanation: 'Muscle types.' },
    { id: 'bio-45', section: SectionType.SHORT_ANSWER, text: '45. Look at this figure and then answer the questions that flow: a. Name the gland which produces estrogen. b. Name three hormones produced from thyroid gland.', type: 'text', correctAnswer: 'a) Ovary. b) Thyroxine (T4), Triiodothyronine (T3), Calcitonin.', marks: 4, topic: 'Endocrine System', explanation: 'Hormones.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_27_33-PM.png' },
    { id: 'bio-46', section: SectionType.SHORT_ANSWER, text: '46. A student fell while playing football and broken his leg. Describe the process that body undergoes to repair the broken bone?', type: 'text', correctAnswer: 'Hematoma formation -> Soft callus -> Hard callus -> Remodeling.', marks: 4, topic: 'Skeletal System', explanation: 'Bone repair.' },
    { id: 'bio-47', section: SectionType.SHORT_ANSWER, text: '47. Compare the structure of DNA and RNA, highlighting their similarities and differences.', type: 'text', correctAnswer: 'DNA: Double strand, Deoxyribose, Thymine. RNA: Single strand, Ribose, Uracil.', marks: 4, topic: 'Genetics', explanation: 'Nucleic acids.' },
    { id: 'bio-48', section: SectionType.SHORT_ANSWER, text: '48. A man with type AB blood is married to a woman with type O blood. They have two natural children and one adopted child. Ahmed has type A blood, Ali has type B blood and Aisha has type O. Which child was adopted?', type: 'text', correctAnswer: 'Aisha (Type O). AB parent cannot pass O allele.', marks: 4, topic: 'Genetics', explanation: 'Blood type inheritance.' },
    { id: 'bio-49', section: SectionType.SHORT_ANSWER, text: '49. The diagram below shows the structure of the neuron. a. Name the parts of neurons labeled 1, 2, 3 and 5. b. Describe the function of the parts 2 and 3.', type: 'text', correctAnswer: 'a) 1: Dendrite, 2: Axon, 3: Myelin Sheath, 5: Terminal. b) Axon carries impulse, Myelin insulates.', marks: 4, topic: 'Nervous System', explanation: 'Neuron structure.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_26_58-PM.png' },
    { id: 'bio-50', section: SectionType.SHORT_ANSWER, text: '50. Briefly explain the difference between lichens and mychorrhiza.', type: 'text', correctAnswer: 'Lichens: Fungi + Algae symbiosis. Mycorrhiza: Fungi + Plant roots symbiosis.', marks: 4, topic: 'Ecology', explanation: 'Symbiotic relationships.' },
    { id: 'bio-51', section: SectionType.SHORT_ANSWER, text: '51. The diagram below shows the structure of a flower: a. Where are the male gametes produced? b. Which part develops into fruit after fertilization?', type: 'text', correctAnswer: 'a) Anther. b) Ovary.', marks: 4, topic: 'Plant Reproduction', explanation: 'Flower anatomy.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_26_50-PM.png' },
    { id: 'bio-52', section: SectionType.SHORT_ANSWER, text: '52. Hemophilia is caused by an X-linked recessive gene. If a hemophiliac man marries a carrier woman: a. What is the probability that their son will have hemophilia? b. What is the probability that their daughter will have hemophilia? c. What is the probability that their daughter will be carrier?', type: 'text', correctAnswer: 'a) 50%. b) 50%. c) 50%.', marks: 6, topic: 'Genetics', explanation: 'Punnett square.' },
    { id: 'bio-53', section: SectionType.SHORT_ANSWER, text: '53. Explain how intracellular enzymes differ from extracellular enzymes.', type: 'text', correctAnswer: 'Intracellular work inside cell (e.g. respiration). Extracellular secreted to work outside (e.g. digestion).', marks: 4, topic: 'Enzymes', explanation: 'Enzyme location.' },
    { id: 'bio-54', section: SectionType.SHORT_ANSWER, text: '54. The diagram below shows the human digestive system. a. Name the parts labeled A, B, C, D. b. State the function of the part labeled D in the digestive system.', type: 'text', correctAnswer: 'a) A: Stomach, B: Small Intestine, C: Large Intestine/Rectum. b) Water absorption/Feces storage.', marks: 4, topic: 'Digestion', explanation: 'Anatomy.', diagramUrl: 'https://shaiyecompany.com/wp-content/uploads/2026/01/ChatGPT-Image-Jan-19-2026-01_26_54-PM.png' },
    { id: 'bio-55', section: SectionType.SHORT_ANSWER, text: '55. Briefly explain the importance of protista.', type: 'text', correctAnswer: 'Producers in aquatic systems (algae), Decomposers, Pathogens (Malaria).', marks: 4, topic: 'Microbiology', explanation: 'Kingdom Protista.' }
  ]
};

export const getExam = (year: number | null, subject: string | null, language: 'english' | 'somali' | 'arabic' = 'english'): Exam | undefined => {
  if (year === 2025) {
    if (subject === 'Mathematics') return MATHEMATICS_2025_EXAM;
    if (subject === 'Geography') return GEOGRAPHY_2025_EXAM;
    if (subject === 'Somali Language') return SOMALI_2025_EXAM;
    if (subject === 'Arabic Language') return ARABIC_2025_EXAM;
    if (subject === 'History') return HISTORY_2025_EXAM;
    if (subject === 'Chemistry') return CHEMISTRY_2025_EXAM;
    if (subject === 'Biology') return BIOLOGY_2025_EXAM;
    if (subject === 'English Language') return ENGLISH_2025_EXAM;
  }
  return undefined;
};
