import { Question, SectionType, Exam } from './types';

export const ACADEMIC_YEARS = [2021, 2022, 2023, 2024, 2025];

export const SUBJECTS = [
  'Physics', 'Mathematics', 'Chemistry', 'Biology', 
  'Geography', 'History', 'Somali Language', 'English Language',
  'Arabic Language', 'Islamic Studies', 'Economics', 'ICT'
];

export const PHYSICS_2025_EXAM: Exam = {
  id: 'phys-2025',
  year: 2025,
  subject: 'Physics',
  durationMinutes: 120,
  direction: 'ltr',
  questions: [
    // --- SECTION A: MULTIPLE CHOICE (40 MARKS) ---
    { id: 'q1', section: SectionType.MCQ, text: 'The branch of physics that deals with motion and force is called :', type: 'mcq', options: ['Optics', 'Mechanics', 'Atomic', 'Electromagnetism'], correctAnswer: 'Mechanics', marks: 1, topic: 'Mechanics', explanation: 'Mechanics is the fundamental branch of physics concerned with the behavior of physical bodies when subjected to forces or displacements.', diagramUrl: '' },
    { id: 'q2', section: SectionType.MCQ, text: 'The magnetic field lines originate from :', type: 'mcq', options: ['East Pole', 'South Pole', 'North Pole', 'West Pole'], correctAnswer: 'North Pole', marks: 1, topic: 'Magnetism', explanation: 'By convention, magnetic field lines are defined to exit from the North pole of a magnet and enter at the South pole.', diagramUrl: '' },
    { id: 'q3', section: SectionType.MCQ, text: 'In which of the following diagrams show P and Q are series with each other and parallel with R.', type: 'mcq', options: ['Diagram (A)', 'Diagram (B)', 'Diagram (C)', 'Diagram (D)'], correctAnswer: 'Diagram (A)', marks: 1, topic: 'Electricity', explanation: 'In Diagram (A), resistors P and Q are connected end-to-end (series). This combination is connected across resistor R, making them parallel.', diagramUrl: '/assets/physics/q3_resistors.png' },
    { id: 'q4', section: SectionType.MCQ, text: 'The period of SHM depends on:', type: 'mcq', options: ['Length of the string', 'Mass of the spring', 'Acceleration due to gravity', 'Mass of vibrating body'], correctAnswer: 'Length of the string', marks: 1, topic: 'SHM', explanation: 'For a simple pendulum, T = 2π√(L/g). The period depends on the length (L) and gravity (g), not mass.', diagramUrl: '' },
    { id: 'q5', section: SectionType.MCQ, text: 'The figure below shows the journey made by a car. At what interval the velocity will be constant?', type: 'mcq', options: ['Between O and K', 'Between L and M', 'Between K and L', 'Between O and M'], correctAnswer: 'Between K and L', marks: 1, topic: 'Kinematics', explanation: 'A horizontal line on a Velocity-Time graph represents constant velocity (zero acceleration).', diagramUrl: '/assets/physics/q5_velocity.png' },
    { id: 'q6', section: SectionType.MCQ, text: 'Which quantity measures the figure below?', type: 'mcq', options: ['Pressure', 'Energy', 'Volume', 'Temperature'], correctAnswer: 'Temperature', marks: 1, topic: 'Thermodynamics', explanation: 'The figure shows a thermometer, which measures Temperature.', diagramUrl: '/assets/physics/q6_thermometer.png' },
    { id: 'q7', section: SectionType.MCQ, text: 'The device used for measuring potential difference (Voltage) is known as :', type: 'mcq', options: ['Ammeter', 'Voltmeter', 'Ohmmeter', 'Galvanometer'], correctAnswer: 'Voltmeter', marks: 1, topic: 'Electricity', explanation: 'A Voltmeter measures potential difference and is connected in parallel.', diagramUrl: '' },
    { id: 'q8', section: SectionType.MCQ, text: 'According to wave properties which property shows the figure below?', type: 'mcq', options: ['Reflection', 'Refraction', 'Diffraction', 'Rectilinear Propagation'], correctAnswer: 'Rectilinear Propagation', marks: 1, topic: 'Light', explanation: 'Light passing through aligned holes demonstrates that light travels in straight lines (Rectilinear Propagation).', diagramUrl: '/assets/physics/q8_rectilinear.png' },
    { id: 'q9', section: SectionType.MCQ, text: 'Two teams from Somali public schools are playing a tug war. Find their resultant force by using the figure below.', type: 'mcq', options: ['600N', '300N', '0N', '0.5N'], correctAnswer: '0N', marks: 1, topic: 'Forces', explanation: 'Forces are equal (300N) and opposite. The resultant force is 300N - 300N = 0N.', diagramUrl: '/assets/physics/q9_tugwar.png' },
    { id: 'q10', section: SectionType.MCQ, text: 'which method of heat transfer occurs in vacuum:', type: 'mcq', options: ['conduction', 'convection', 'radiation', 'induction'], correctAnswer: 'radiation', marks: 1, topic: 'Heat', explanation: 'Radiation travels via electromagnetic waves and requires no medium, allowing it to pass through a vacuum.', diagramUrl: '' },
    { id: 'q11', section: SectionType.MCQ, text: 'In the early morning the sun can cause the buildings to form a shadow. This shadow appears:', type: 'mcq', options: ['Long', 'fat', 'thin', 'short'], correctAnswer: 'Long', marks: 1, topic: 'Light', explanation: 'Low angle of the sun in the morning creates long shadows.', diagramUrl: '' },
    { id: 'q12', section: SectionType.MCQ, text: 'In the figure shows pendulums with different strings, each pendulum is pulled to the sides and are released. Which of the of the pendulums oscillates with the lowest frequency?', type: 'mcq', options: ['String A', 'string B', 'string C', 'string D'], correctAnswer: 'string D', marks: 1, topic: 'Waves', explanation: 'Frequency is inversely proportional to length. The longest string (D) has the lowest frequency.', diagramUrl: '/assets/physics/q12_pendulums.png' },
    { id: 'q13', section: SectionType.MCQ, text: 'The third law of Newton is also known as:', type: 'mcq', options: ['The law of inertia', 'law of acceleration', 'The law of action and reaction', 'The law of weight'], correctAnswer: 'The law of action and reaction', marks: 1, topic: 'Mechanics', explanation: 'Newton\'s Third Law: Action and Reaction are equal and opposite.', diagramUrl: '' },
    { id: 'q14', section: SectionType.MCQ, text: 'The figure below shows one of the following motion', type: 'mcq', options: ['Linear Motion', 'Projectile Motion', 'Circular Motion', 'Oscillatory Motion'], correctAnswer: 'Projectile Motion', marks: 1, topic: 'Kinematics', explanation: 'The parabolic curve represents Projectile Motion.', diagramUrl: '/assets/physics/q14_projectile.png' },
    { id: 'q15', section: SectionType.MCQ, text: 'The Quantity of heat energy is given by :', type: 'mcq', options: ['Q = mcΔt', 'Q = mL', 'Q = I²Rt', 'Q = VIt'], correctAnswer: 'Q = mcΔt', marks: 1, topic: 'Heat', explanation: 'Q = mcΔt is the formula for heat energy change due to temperature difference.', diagramUrl: '' },
    { id: 'q16', section: SectionType.MCQ, text: 'In the diaagram belaw the amplitude the wave in centimeters is equivalent to:', type: 'mcq', options: ['1cm', '2cm', '3cm', '4cm'], correctAnswer: '4cm', marks: 1, topic: 'Waves', explanation: 'The peak of the wave is at 4 on the vertical axis.', diagramUrl: '/assets/physics/q16_wave.png' },
    { id: 'q17', section: SectionType.MCQ, text: 'Which of the following materials allows light to pass through it ?', type: 'mcq', options: ['Copper', 'wood', 'glass', 'rubber'], correctAnswer: 'glass', marks: 1, topic: 'Light', explanation: 'Glass is transparent.', diagramUrl: '' },
    { id: 'q18', section: SectionType.MCQ, text: 'The frequency of simple harmonic motion is given by:', type: 'mcq', options: ['f = 1/2π √(k/m)', 'f = 1/2π √(m/k)', 'f = 2π √(k/m)', 'f = 2π √(m/k)'], correctAnswer: 'f = 1/2π √(k/m)', marks: 1, topic: 'SHM', explanation: 'Correct formula: f = (1/2π) * √(k/m). (Option A in the provided diagram).', diagramUrl: '/assets/physics/q18_formulas.png' },
    { id: 'q19', section: SectionType.MCQ, text: 'In the following shapes represents same brick place in different ways which case has its least pressure:', type: 'mcq', options: ['Shape A', 'Shape B', 'Shape C', 'All equal'], correctAnswer: 'Shape C', marks: 1, topic: 'Pressure', explanation: 'Pressure is Force/Area. Shape C has the largest contact area, resulting in the least pressure.', diagramUrl: '' },
    { id: 'q20', section: SectionType.MCQ, text: 'The characteristics of sound which helps us to distinguish between a woman’s voice and man’s, even voice without seeing them is :', type: 'mcq', options: ['Intensity', 'Loudness', 'Quality', 'Pitch'], correctAnswer: 'Pitch', marks: 1, topic: 'Sound', explanation: 'Pitch distinguishes high frequency (woman) from low frequency (man) voices.', diagramUrl: '' },
    { id: 'q21', section: SectionType.MCQ, text: 'A microphone of a mosque is set up to record and display a sound of pray(Salat) made by loudspeaker. Which one of the following sound is louder?', type: 'mcq', options: ['Graph a', 'Graph b', 'Graph c', 'Graph d'], correctAnswer: 'Graph d', marks: 1, topic: 'Sound', explanation: 'Graph D has the largest amplitude (vertical height), which corresponds to loudness.', diagramUrl: '/assets/physics/q21_sound.png' },
    { id: 'q22', section: SectionType.MCQ, text: 'The angle between two plane mirrors is 60°. if an object is placed between them, the number of images formed will be', type: 'mcq', options: ['6 images', '5 images', '4 images', '3 images'], correctAnswer: '5 images', marks: 1, topic: 'Light', explanation: 'n = (360/60) - 1 = 5 images.', diagramUrl: '' },
    { id: 'q23', section: SectionType.MCQ, text: 'The image formed by a plane mirror is', type: 'mcq', options: ['real and erect', 'virtual and inverted', 'virtual and erect', 'real and magnified'], correctAnswer: 'virtual and erect', marks: 1, topic: 'Optics', explanation: 'Plane mirrors form virtual, erect images.', diagramUrl: '' },
    { id: 'q24', section: SectionType.MCQ, text: 'A battery of 220V is connected to a lamp as shown in the figure. The current passed through it is', type: 'mcq', options: ['220V', '176V', '275A', '220.8V'], correctAnswer: '275A', marks: 1, topic: 'Electricity', explanation: 'I = V/R = 220 / 0.8 = 275A.', diagramUrl: '/assets/physics/q24_circuit.png' },
    { id: 'q25', section: SectionType.MCQ, text: 'The principle of formation of image in lenses is :', type: 'mcq', options: ['Reflection of light', 'Refraction of light', 'Dispersion of light', 'Scattering of light'], correctAnswer: 'Refraction of light', marks: 1, topic: 'Light', explanation: 'Lenses work by refracting light.', diagramUrl: '' },
    { id: 'q26', section: SectionType.MCQ, text: 'If you stand in front of a special mirror and you see that the image of your head is bigger than Normal, the middle part of your body is same size and your legs is smaller than normal. The special mirror is made up of:', type: 'mcq', options: ['Plane, Concave, Convex', 'Concave, Plane, Convex', 'convex, Plane, Concave', 'Plane, Convex, Concave'], correctAnswer: 'Concave, Plane, Convex', marks: 1, topic: 'Optics', explanation: 'Concave magnifies (head), Plane keeps size (body), Convex diminishes (legs).', diagramUrl: '' },
    { id: 'q27', section: SectionType.MCQ, text: 'A coal appears dark when viewed with white light because it ...................... All light falling on it.', type: 'mcq', options: ['Reflect', 'Disperse', 'Refract', 'Absorb'], correctAnswer: 'Absorb', marks: 1, topic: 'Light', explanation: 'Black objects absorb all light.', diagramUrl: '/assets/physics/q27_coal.png' },
    { id: 'q28', section: SectionType.MCQ, text: 'The stars appears to twinkle due to:', type: 'mcq', options: ['refraction', 'diffraction', 'interference', 'reflection'], correctAnswer: 'refraction', marks: 1, topic: 'Space', explanation: 'Atmospheric refraction causes twinkling.', diagramUrl: '' },
    { id: 'q29', section: SectionType.MCQ, text: 'The seven colors obtained in the screen when white light passes through a prism is known as.', type: 'mcq', options: ['Scattering', 'Refraction', 'Spectrum', 'Dispersion'], correctAnswer: 'Spectrum', marks: 1, topic: 'Light', explanation: 'The band of dispersed colors is called a spectrum.', diagramUrl: '/assets/physics/q29_prism.png' },
    { id: 'q30', section: SectionType.MCQ, text: 'Calculate the equivalent capacitors as shown in the figure below', type: 'mcq', options: ['3.4uF', '2.4uF', '4.4uF', '5.4uF'], correctAnswer: '2.4uF', marks: 1, topic: 'Electricity', explanation: 'Series: 1/C = 1/4 + 1/6. C = 2.4uF.', diagramUrl: '' },
    { id: 'q31', section: SectionType.MCQ, text: 'In real life the faraday’s law can be applied in many devices which of the following is an application of it.', type: 'mcq', options: ['Electric bulb', 'Watches', 'televisions', 'tape player'], correctAnswer: 'tape player', marks: 1, topic: 'Electromagnetism', explanation: 'Tape players use electromagnetic induction.', diagramUrl: '' },
    { id: 'q32', section: SectionType.MCQ, text: 'The maximum voltage circuit is 60V. using θ = 30° its instantaneous voltage will be', type: 'mcq', options: ['40V', '50V', '30V', '60V'], correctAnswer: '30V', marks: 1, topic: 'Electricity', explanation: 'v = Vmax sin(30) = 60 * 0.5 = 30V.', diagramUrl: '' },
    { id: 'q33', section: SectionType.MCQ, text: 'The basic elements in DC is resistor while in AC the basic elements are:', type: 'mcq', options: ['Resistor, Inductor and Capacitor', 'Voltage, Diode and Capacitor', 'Transistor, Diode and Resistor', 'Diode, Inductor and Resistors'], correctAnswer: 'Resistor, Inductor and Capacitor', marks: 1, topic: 'Electricity', explanation: 'AC circuits use R, L, and C.', diagramUrl: '' },
    { id: 'q34', section: SectionType.MCQ, text: 'The below figure represents :', type: 'mcq', options: ['AND gate', 'OR gate', 'NOT gate', 'NOR gate'], correctAnswer: 'AND gate', marks: 1, topic: 'Electronics', explanation: 'The symbol shown is a D-shaped AND gate.', diagramUrl: '/assets/physics/q34_gate.png' },
    { id: 'q35', section: SectionType.MCQ, text: 'The two most frequently used materials for electronics are', type: 'mcq', options: ['Carbon and Selenium', 'Selenium and Glass', 'Germanium and Silicon', 'Gallium and Arsenic'], correctAnswer: 'Germanium and Silicon', marks: 1, topic: 'Electronics', explanation: 'Si and Ge are the standard semiconductors.', diagramUrl: '' },
    { id: 'q36', section: SectionType.MCQ, text: 'Which of the following electromagnetic spectrum is particularly more hazardous', type: 'mcq', options: ['γ – ray', 'Infrared', 'X – ray', 'Ultraviolet'], correctAnswer: 'γ – ray', marks: 1, topic: 'Radiation', explanation: 'Gamma rays are the most energetic and hazardous.', diagramUrl: '' },
    { id: 'q37', section: SectionType.MCQ, text: 'The different elements having same mass number but different atomic number are called :', type: 'mcq', options: ['isobars', 'isotones', 'isotopes', 'isomers'], correctAnswer: 'isobars', marks: 1, topic: 'Nuclear', explanation: 'Isobars have same mass number, different atomic number.', diagramUrl: '' },
    { id: 'q38', section: SectionType.MCQ, text: 'Rn -> Po + He + Energy. This equation represents a radioactive emission of:', type: 'mcq', options: ['Alpha Particle', 'Beta Particle', 'Gamma Particle', 'Theta Particle'], correctAnswer: 'Alpha Particle', marks: 1, topic: 'Nuclear', explanation: 'Emission of Helium nucleus (He) indicates Alpha decay.', diagramUrl: '/assets/physics/q38_nuclear.png' },
    { id: 'q39', section: SectionType.MCQ, text: 'Which type of radiation is stopped by a sheet paper ?', type: 'mcq', options: ['Beta particle', 'Alpha particle', 'Gamma ray', 'X-ray'], correctAnswer: 'Alpha particle', marks: 1, topic: 'Nuclear', explanation: 'Alpha particles are easily stopped by paper.', diagramUrl: '' },
    { id: 'q40', section: SectionType.MCQ, text: 'For every one degree Celsius rise in temperature the speed of sound in air is increased by', type: 'mcq', options: ['0.4 m/s', '0.2 m/s', '0.6 m/s', '0.1 m/s'], correctAnswer: '0.6 m/s', marks: 1, topic: 'Sound', explanation: 'Speed of sound increases by approx 0.6 m/s per °C.', diagramUrl: '' },

    // --- PART TWO: DIRECT QUESTIONS (28 MARKS) ---
    { id: 'b1', section: SectionType.SHORT_ANSWER, text: '1. a) What is a magnet? \n a) What are the poles of magnet ?', type: 'text', correctAnswer: 'A magnet is a material that produces a magnetic field. Poles are North and South.', marks: 8, topic: 'Magnetism', explanation: 'Defined by magnetic field creation and N/S poles.', diagramUrl: '' },
    { id: 'b2', section: SectionType.SHORT_ANSWER, text: '2. Complete the table below with the names of the type of current which generated the specific wave front', type: 'text', correctAnswer: '1) Direct Current (DC). 2) Alternating Current (AC).', marks: 4, topic: 'Electricity', explanation: 'Flat line = DC. Sine wave = AC.', diagramUrl: '/assets/physics/b2_table.png' },
    { id: 'b3', section: SectionType.SHORT_ANSWER, text: '3. Distinguish between transparent and translucent materials.', type: 'text', correctAnswer: 'Transparent allows all light; Translucent allows some but scatters it.', marks: 4, topic: 'Light', explanation: 'Clear vs. Frosted/Cloudy visibility.', diagramUrl: '' },
    { id: 'b4', section: SectionType.SHORT_ANSWER, text: '4. List the five common properties of wave.', type: 'text', correctAnswer: 'Reflection, Refraction, Diffraction, Interference, Polarization.', marks: 4, topic: 'Waves', explanation: 'Standard wave behaviors.', diagramUrl: '' },
    { id: 'b5', section: SectionType.SHORT_ANSWER, text: '5. Compare with examples luminous and non – luminous bodies.', type: 'text', correctAnswer: 'Luminous emit own light (Sun); Non-luminous reflect light (Moon).', marks: 4, topic: 'Light', explanation: 'Source of light vs reflector.', diagramUrl: '' },
    { id: 'b6', section: SectionType.SHORT_ANSWER, text: '6. Give reason why the red light is used as a universal danger signal ?', type: 'text', correctAnswer: 'Longest wavelength, least scattering, visible from distance.', marks: 4, topic: 'Light', explanation: 'Red scatters least in fog/smoke.', diagramUrl: '' },
    { id: 'b7', section: SectionType.SHORT_ANSWER, text: '7. a) Name the defect of vision suffering from him. \n b) Name the type of lens used to correct his defect.', type: 'text', correctAnswer: 'a) Myopia (short-sightedness). b) Concave (diverging) lens.', marks: 4, topic: 'Light', explanation: 'Cannot see far = Myopia. Corrected by Concave.', diagramUrl: '' },

    // --- PART THREE: CALCULATIONS (32 MARKS) ---
    { id: 'c8', section: SectionType.CALCULATION, text: '8. The yacht shown in figure 1 has amass of 6200kg. Calculate its weight in air. Take Acceleration due to gravity g=10 m/s²?', type: 'text', correctAnswer: '62,000 N', marks: 4, topic: 'Mechanics', explanation: 'W = mg = 6200 * 10 = 62,000N.', diagramUrl: '/assets/physics/c8_yacht.png' },
    { id: 'c9', section: SectionType.CALCULATION, text: '9. The minute arm of the clock rotates in one complete revolution (2π) in 60 seconds. Calculate the angular frequency of the arm.', type: 'text', correctAnswer: '0.105 rad/s (π/30)', marks: 4, topic: 'Circular Motion', explanation: 'ω = 2π/T = 2π/60 = π/30 rad/s.', diagramUrl: '/assets/physics/c9_clock.png' },
    { id: 'c10', section: SectionType.CALCULATION, text: '10. Find the intensity level for a sound wave of intensity of 4 × 10⁻⁶ w/m².', type: 'text', correctAnswer: '66 dB (approx)', marks: 4, topic: 'Sound', explanation: 'L = 10 log(I/Io).', diagramUrl: '' },
    { id: 'c11', section: SectionType.CALCULATION, text: '11. The primary current in a transformer is 20 A if the primary coil has 200 turns and secondary coil has 600 turns. What current follow in the secondary coil.', type: 'text', correctAnswer: '6.67 A', marks: 4, topic: 'Electricity', explanation: 'Ip/Is = Ns/Np. 20/Is = 600/200. Is = 6.67A.', diagramUrl: '/assets/physics/c11_transformer.png' },
    { id: 'c12', section: SectionType.CALCULATION, text: '12. An electron is accelerated by a potential difference of 2000 V if the electron charge is 1.6 x 10^-19 C what is the electron energy in a) Joule(J) b) Electron volt(e.V).', type: 'text', correctAnswer: 'a) 3.2e-16 J. b) 2000 eV.', marks: 4, topic: 'Electricity', explanation: 'E = qV.', diagramUrl: '' },
    { id: 'c13', section: SectionType.CALCULATION, text: '13. Calculate the equivalent resistance as shown below', type: 'text', correctAnswer: '1.33 Ω', marks: 4, topic: 'Electricity', explanation: 'Parallel formula 1/R = 1/R1 + 1/R2...', diagramUrl: '' },
    { id: 'c14', section: SectionType.CALCULATION, text: '14. A student having s myopic eye uses a concave lens of focal length 15cm. what is the power of the lens?', type: 'text', correctAnswer: '-6.67 D', marks: 4, topic: 'Light', explanation: 'P = 1/f (in meters). f = -0.15m.', diagramUrl: '' },
    { id: 'c15', section: SectionType.CALCULATION, text: '15. A 20 cm straight wire moves at a constant speed of 5 m/s perpendicular to a magnetic field of strength 0.004 T. \n a) How much induced electromotive force is generated in the wire? \n b) If the wire has a resistance of 0.25Ω what is the magnitude of the current passing through it?', type: 'text', correctAnswer: 'a) 0.004 V. b) 0.016 A.', marks: 4, topic: 'Magnetism', explanation: 'EMF = BLv.', diagramUrl: '' }
  ]
};

export const ARABIC_2025_EXAM: Exam = {
  id: 'arabic-2025',
  year: 2025,
  subject: 'Arabic Language',
  durationMinutes: 120,
  direction: 'rtl',
  sectionPassages: {
    [SectionType.MCQ]: `القسم الأول: الفهم والإستيعاب
الكرم هو صفة محمودة من صفات البشر، وهو الإنفاق وإعطاء المال لمن يحتاج إليه ابتغاء وجه الله الكريم، ويفضل أن يتحلى بها كل إنسان، ولها أهمية كبيرة في المجتمع حيث أنها تساعد على نشر مبدأ الأخوة والرحمة بين الناس، بالإضافة إلى ذلك يعد الكرم من الأشياء التي تؤدي إلى تحبيب الناس بعضهم لبعض، حيث ينتفع الإنسان الكريم بحب الآخرين من حوله، فهو دائم العطاء ويسرع دائماً في مساعدة المحتاج، ولا يبخل عليهم بأي شيء مهما كان قليلاً من إمكانياته.

ينبغي أن يكون المسلم كريماً في قوله وفعله، ولا يقتصر الكرم على المال فقط، وليس يقتصر تأثير الرسول صلى الله عليه وسلم على الناس بالكلام فقط، بل كان قدوة في أفعاله، والدليل على ذلك ما فعله الرسول صلى الله عليه وسلم عند مجيء رجل من المشركين، فأكرمه الرسول صلى الله عليه وسلم وأعطاه طعاماً، وتساعد الرجل إلى قومه داعياً للدخول في الإسلام قائلاً: "أسلموا فإن محمداً يعطي عطاء من لا يخاف الفقر".

وهكذا المواقف تظهر تأثير الكرم، ثم تحول إلى دعوة لينشر الدين الإسلامي في كل مكان يوجد فيه الناس، وكان الرسول صلى الله عليه وسلم دائماً مثالاً يحتذى به في الكرم، فقد كان كريماً يعطي الناس، ويحثهم على الخير، وكان من خلقه الكرم.

قال تعالى في سورة البقرة:
(وَمَا أَنفَقْتُم مِّن شَيْءٍ فَهُوَ يُخْلِفُهُ وَهُوَ خَيْرُ الرَّازِقِينَ)

وقال رسول الله صلى الله عليه وسلم: "ما نقص مال عبد من صدقة".

وقال صلى الله عليه وسلم: "إن الله كريم يحب الكرم".

الشعوب الصومالية معروفة بالكرم، ومن العادات الطيبة لدى الصوماليين التسابق في سبيل التكافل، سواء كانوا مسافرين أم مقيمين، وهناك عادات أخرى يتميز بها الصوماليون من غيرهم من الأمم منها صرف رسوم المشروبات والوجبات الخفيفة في المناسبات، والتضحية من أجل شخص واحد، وضمان تكلفة السفر لمن قطع الزاد عنه، وتقديم القرى للضيوف والمسافرين، فمشاكل المادة لم تمنع الصوماليين من تمسكهم بهذه العادات.

وهذا النوع من الإيثار يبرز قيمة التضحية، وهو ما يعزز قيم التعاون والتكافل، خاصة بين أبناء الصوماليين في غربتهم، ومساهمتهم الكبيرة في المجتمعات التي يعيشون بها، والوطن لهم جميعاً، ويطيرون.

ومن المهم أن نستمر في إدارة المصائب وتخفيف خسائرها، وذلك لن يتحقق إلا بالكرم والتعاون، وأن نقتدي بآبائنا وأجدادنا من هذه الصفة الطيبة، وأن نواصل غرسها في الأجيال الصاعدة للأمة الصومالية.`
  },
  questions: [
    // --- SECTION A: MCQ (40 MARKS) ---
    { id: 'arb-1', section: SectionType.MCQ, text: '1. ضد كلمة "الكرم":', type: 'mcq', options: ['الحقد', 'الحسد', 'الترف', 'البخل'], correctAnswer: 'البخل', marks: 1, topic: 'Vocabulary', explanation: 'الكلمة (الكرم) تعني الجود والعطاء، وضدها (البخل) وهو الإمساك والشح.' },
    { id: 'arb-2', section: SectionType.MCQ, text: '2. إعراب كلمة "فظلوماً":', type: 'mcq', options: ['مفعول به', 'مفعول لأجله', 'مفعول معه', 'مفعول فيه'], correctAnswer: 'مفعول به', marks: 1, topic: 'Grammar', explanation: 'كلمة (فظلوماً) وقع عليها فعل الفاعل، وهي منصوبة، لذا تعرب مفعولاً به.' },
    { id: 'arb-3', section: SectionType.MCQ, text: '3. الجماليات البديعية التي توجد في كلمتي "نقلاً، ثقلاً":', type: 'mcq', options: ['الجناس', 'المقابلة', 'السجع', 'الطباق'], correctAnswer: 'السجع', marks: 1, topic: 'Rhetoric', explanation: 'اتفاق فواصل الجمل في الحرف الأخير يسمى سجعاً.' },
    { id: 'arb-4', section: SectionType.MCQ, text: '4. مفرد كلمة "الأدلة":', type: 'mcq', options: ['دليل', 'دلالة', 'دلائل', 'مدلول'], correctAnswer: 'دليل', marks: 1, topic: 'Vocabulary', explanation: 'مفرد كلمة (الأدلة) هو (دليل). أما (دلائل) فمفردها (دلالة) أو (دليل) أحياناً، لكن الأدلة جمع تكسير لـ دليل.' },
    { id: 'arb-5', section: SectionType.MCQ, text: '5. مرادف كلمة "التعاون":', type: 'mcq', options: ['الإيثار', 'التضحية', 'التكافل', 'النصيحة'], correctAnswer: 'التكافل', marks: 1, topic: 'Vocabulary', explanation: 'التعاون يعني المشاركة والمساعدة المتبادلة، وأقرب معنى له هو التكافل.' },
    { id: 'arb-6', section: SectionType.MCQ, text: '6. عبارة "ما أوجعنا أن نفتدي بأبنائنا!" فيها:', type: 'mcq', options: ['اسم الفاعل', 'اسم المفعول', 'صيغة التعجب', 'صيغة المصدر'], correctAnswer: 'صيغة التعجب', marks: 1, topic: 'Grammar', explanation: 'صيغة (ما أفعله) مثل (ما أوجعنا) هي صيغة قياسية للتعجب.' },
    { id: 'arb-7', section: SectionType.MCQ, text: '7. عكس كلمة "مسافر":', type: 'mcq', options: ['مقيم', 'مؤقت', 'مبيت', 'مواطن'], correctAnswer: 'مقيم', marks: 1, topic: 'Vocabulary', explanation: 'المسافر هو من ينتقل، وعكسه المقيم وهو الثابت في مكانه.' },
    { id: 'arb-8', section: SectionType.MCQ, text: '8. مفرد كلمة "دعاة":', type: 'mcq', options: ['داعية', 'دعاء', 'مدعي', 'دعوات'], correctAnswer: 'داعية', marks: 1, topic: 'Vocabulary', explanation: 'مفرد (دعاة) هو (داعية).' },
    { id: 'arb-9', section: SectionType.MCQ, text: '9. كلمة "خسائر" هي جمع:', type: 'mcq', options: ['جمع التكسير', 'جمع المذكر السالم', 'جمع المؤنث السالم', 'اسم جمع'], correctAnswer: 'جمع التكسير', marks: 1, topic: 'Grammar', explanation: 'كلمة (خسائر) مفردها (خسارة)، وتغيرت بنية المفرد عند الجمع، فهو جمع تكسير (صيغة منتهى الجموع).' },
    { id: 'arb-10', section: SectionType.MCQ, text: '10. المقصود بـ "المحن":', type: 'mcq', options: ['المظاهر', 'المجن', 'المصائب', 'المسائل'], correctAnswer: 'المصائب', marks: 1, topic: 'Vocabulary', explanation: 'المحن جمع محنة وهي البلية والمصيبة.' },
    { id: 'arb-11', section: SectionType.MCQ, text: '11. ضد كلمة "الغنى":', type: 'mcq', options: ['الفقر', 'القفز', 'اليسر', 'القرف'], correctAnswer: 'الفقر', marks: 1, topic: 'Vocabulary', explanation: 'الغنى هو الكفاية، وضده الفقر والحاجة.' },
    { id: 'arb-12', section: SectionType.MCQ, text: '12. جمع كلمة "جبل":', type: 'mcq', options: ['أجبال', 'جبال', 'جبلون', 'جبيلات'], correctAnswer: 'جبال', marks: 1, topic: 'Vocabulary', explanation: 'جمع جبل هو جبال.' },
    { id: 'arb-13', section: SectionType.MCQ, text: '13. "يتمتع الإنسان الكريم بحب الآخرين" كلمة "يتمتع" فعل مضارع:', type: 'mcq', options: ['مرفوع', 'منصوب', 'مجزوم', 'مبني'], correctAnswer: 'مرفوع', marks: 1, topic: 'Grammar', explanation: 'الفعل المضارع (يتمتع) لم يسبقه ناصب ولا جازم، فهو مرفوع.' },
    { id: 'arb-14', section: SectionType.MCQ, text: '14. من أدوات النصب التي وردت في القطعة:', type: 'mcq', options: ['حتى', 'أن', 'لم', 'لما'], correctAnswer: 'أن', marks: 1, topic: 'Grammar', explanation: '(أن) حرف مصدري ونصب.' },
    { id: 'arb-15', section: SectionType.MCQ, text: '15. ميزان كلمة "مساعِدة":', type: 'mcq', options: ['مفاعيل', 'مفاعلة', 'مفعيل', 'مفتعلة'], correctAnswer: 'مفاعلة', marks: 1, topic: 'Morphology', explanation: 'مساعدة على وزن مفاعلة.' },
    { id: 'arb-16', section: SectionType.MCQ, text: '16. "شربت ماء زمزم" هذه الجملة فيها مجاز مرسل علاقته:', type: 'mcq', options: ['السببية', 'الجزئية', 'المحلية', 'الكلية'], correctAnswer: 'الكلية', marks: 1, topic: 'Rhetoric', explanation: 'ذكر الكل (ماء زمزم) وأراد الجزء (بعض الماء أو شربة منه)، فالعلاقة الكلية.' },
    { id: 'arb-17', section: SectionType.MCQ, text: '17. من أدوات النداء:', type: 'mcq', options: ['هل', 'يا', 'إن', 'لم'], correctAnswer: 'يا', marks: 1, topic: 'Grammar', explanation: '(يا) هي أداة نداء.' },
    { id: 'arb-18', section: SectionType.MCQ, text: '18. التشبيه الذي يكون فيه وجه الشبه منتزعاً من متعدد يسمى تشبيهاً:', type: 'mcq', options: ['تمثيلياً', 'مفصلاً', 'مفرداً', 'بليغاً'], correctAnswer: 'تمثيلياً', marks: 1, topic: 'Rhetoric', explanation: 'التشبيه التمثيلي هو ما انتزع فيه وجه الشبه من متعدد.' },
    { id: 'arb-19', section: SectionType.MCQ, text: '19. هذه طائرة "سريعة"، الموقع الإعرابي لكلمة "سريعة":', type: 'mcq', options: ['بدل', 'توكيد', 'نعت', 'عطف'], correctAnswer: 'نعت', marks: 1, topic: 'Grammar', explanation: 'كلمة (سريعة) تصف النكرة قبلها (طائرة) وتطابقها، فهي نعت (صفة).' },
    { id: 'arb-20', section: SectionType.MCQ, text: '20. "الفتاة ناعمة الكفين" في هذه الجملة:', type: 'mcq', options: ['استعارة', 'تشبيه', 'مجاز مرسل', 'كناية'], correctAnswer: 'كناية', marks: 1, topic: 'Rhetoric', explanation: 'كناية عن صفة (الراحة، الترف، عدم العمل الشاق). الكناية هي إطلاق اللفظ وإرادة لازم معناه.' },
    { id: 'arb-21', section: SectionType.MCQ, text: '21. يصاغ اسم المفعول من الفعل المضارع غير الثلاثي (أقام) ويكون:', type: 'mcq', options: ['مقيماً', 'مقامة', 'مقام', 'إقامة'], correctAnswer: 'مقيماً', marks: 1, topic: 'Morphology', explanation: 'التصحيح: اسم المفعول هو (مُقام). الخيارات قد تكون غير دقيقة، لكن القاعدة هي ضم الأول وفتح ما قبل الآخر.' },
    { id: 'arb-22', section: SectionType.MCQ, text: '22. ما حذف المشبه به وذكر المشبه يسمى استعارة:', type: 'mcq', options: ['أصلية', 'تصريحية', 'مكنية', 'مرشحة'], correctAnswer: 'مكنية', marks: 1, topic: 'Rhetoric', explanation: 'الاستعارة المكنية هي التي ذُكر فيها المشبه وحُذف المشبه به مع بقاء شيء من لوازمه.' },
    { id: 'arb-23', section: SectionType.MCQ, text: '23. اتفاق أواخر الجمل في الحروف يسمى:', type: 'mcq', options: ['استهلالية', 'جناساً', 'سجعاً', 'طباقاً'], correctAnswer: 'سجعاً', marks: 1, topic: 'Rhetoric', explanation: 'السجع هو توافق الفواصل.' },
    { id: 'arb-24', section: SectionType.MCQ, text: '24. من معاني "في":', type: 'mcq', options: ['الابتدائية', 'السببية', 'البدلية', 'الظرفية'], correctAnswer: 'الظرفية', marks: 1, topic: 'Grammar', explanation: 'تفيد الظرفية.' },
    { id: 'arb-25', section: SectionType.MCQ, text: '25. المقصود بكلمة "الظلم":', type: 'mcq', options: ['الكفاح', 'الاستعمار', 'الضيم', 'الاحتلال'], correctAnswer: 'الضيم', marks: 1, topic: 'Vocabulary', explanation: 'الظلم مرادفه الجور والضيم.' },
    { id: 'arb-26', section: SectionType.MCQ, text: '26. معنى كلمة "الجليس":', type: 'mcq', options: ['الصاحب', 'الشريك', 'الجواد', 'الكريم'], correctAnswer: 'الصاحب', marks: 1, topic: 'Vocabulary', explanation: 'الجليس هو الصاحب والمرافق.' },
    { id: 'arb-27', section: SectionType.MCQ, text: '27. قال المعلم للطلاب: "ضعوا الأقلام" استخدم علامة الترقيم في المكان الخاطئ:', type: 'mcq', options: ['(؟)', '(:)', '(!)', '(")'], correctAnswer: '(؟)', marks: 1, topic: 'Punctuation', explanation: 'الجملة طلبية (أمر) لا استفهام فيها، لذا علامة الاستفهام (؟) خاطئة هنا.' },
    { id: 'arb-28', section: SectionType.MCQ, text: '28. ضد كلمة "ينام":', type: 'mcq', options: ['يقوم', 'يحضر', 'يستيقظ', 'يأتي'], correctAnswer: 'يستيقظ', marks: 1, topic: 'Vocabulary', explanation: 'النوم ضده الاستيقاظ (اليقظة).' },
    { id: 'arb-29', section: SectionType.MCQ, text: '29. معنى كلمة "القصر" في البلاغة:', type: 'mcq', options: ['الحبس', 'المبنى', 'الحذف', 'المساواة'], correctAnswer: 'الحبس', marks: 1, topic: 'Rhetoric', explanation: 'القصر لغة هو الحبس، واصطلاحاً تخصيص شيء بشيء بطريق مخصوص.' },
    { id: 'arb-30', section: SectionType.MCQ, text: '30. الصياغة الصحيحة للجملة التي فيها حال هي:', type: 'mcq', options: ['رأيت المعلم مبتسمًا', 'رأيت المعلم المبتسم', 'جعلت الطين حجرًا', 'سمعت الخبر المفرح'], correctAnswer: 'رأيت المعلم مبتسمًا', marks: 1, topic: 'Grammar', explanation: 'الحال اسم نكرة منصوب مشتق يبين هيئة صاحبه. (مبتسماً) حال منصوبة.' },
    { id: 'arb-31', section: SectionType.MCQ, text: '31. مرادف كلمة "ود":', type: 'mcq', options: ['حب', 'كره', 'بغض', 'حقد'], correctAnswer: 'حب', marks: 1, topic: 'Vocabulary', explanation: 'الود هو الحب والمحبة.' },
    { id: 'arb-32', section: SectionType.MCQ, text: '32. الشاعر أحمد بن حسن أبو الطيب المتنبي من شعراء العصر:', type: 'mcq', options: ['صدر الإسلام', 'الأموي', 'العباسي', 'الحديث'], correctAnswer: 'العباسي', marks: 1, topic: 'Literature', explanation: 'المتنبي من شعراء العصر العباسي.' },
    { id: 'arb-33', section: SectionType.MCQ, text: '33. عاد الطالب منصوراً، إعراب كلمة "منصوراً":', type: 'mcq', options: ['تمييز', 'حال', 'نعت', 'مفعول به'], correctAnswer: 'حال', marks: 1, topic: 'Grammar', explanation: 'منصوراً حال منصوبة.' },
    { id: 'arb-34', section: SectionType.MCQ, text: '34. المقصود بـ "كلمة البين":', type: 'mcq', options: ['الخصام', 'الفراق', 'السباق', 'القتال'], correctAnswer: 'الفراق', marks: 1, topic: 'Vocabulary', explanation: 'البين (بفتح الباء) هو الفراق والبعد. قال الشاعر: "بان الأحبة".' },
    { id: 'arb-35', section: SectionType.MCQ, text: '35. جمع كلمة "سجية":', type: 'mcq', options: ['سجيات', 'سجين', 'سجايا', 'سجون'], correctAnswer: 'سجايا', marks: 1, topic: 'Vocabulary', explanation: 'جمع سجية هو سجايا.' },
    { id: 'arb-36', section: SectionType.MCQ, text: '36. في كلمة "الهُعخع" عيب من عيوب الفصاحة وهو:', type: 'mcq', options: ['تنافر الكلمات', 'التعقيد', 'تنافر الحروف', 'مخالفة القياس'], correctAnswer: 'تنافر الحروف', marks: 1, topic: 'Rhetoric', explanation: 'كلمة (الهعخع) مثال مشهور لتنافر الحروف بسبب اجتماع حروف الحلق، مما يصعب نطقها.' },
    { id: 'arb-37', section: SectionType.MCQ, text: '37. من أسماء الإشارة القريبة:', type: 'mcq', options: ['أولئك', 'تلك', 'ذلك', 'هذا'], correctAnswer: 'هذا', marks: 1, topic: 'Grammar', explanation: 'هذا اسم إشارة للقريب.' },
    { id: 'arb-38', section: SectionType.MCQ, text: '38. فإن رُزِقتَ خليفةً محمودةً ... قائل هذا البيت هو:', type: 'mcq', options: ['حافظ إبراهيم', 'محمود غنيم', 'أحمد محمد', 'محمود الرصافي'], correctAnswer: 'حافظ إبراهيم', marks: 1, topic: 'Literature', explanation: 'البيت من قصيدة للشاعر حافظ إبراهيم (شاعر النيل).' },
    { id: 'arb-39', section: SectionType.MCQ, text: '39. مفرد كلمة "منايا":', type: 'mcq', options: ['أمان', 'أمنية', 'منية', 'منون'], correctAnswer: 'منية', marks: 1, topic: 'Vocabulary', explanation: 'المنايا جمع مَنِيَّة (بفتح الميم وكسر النون وتشديد الياء) وهي الموت أو القدر.' },
    { id: 'arb-40', section: SectionType.MCQ, text: '40. معنى كلمة "الإملاق":', type: 'mcq', options: ['الفشل', 'الإخفاق', 'الفقر', 'الشدّة'], correctAnswer: 'الفقر', marks: 1, topic: 'Vocabulary', explanation: 'الإملاق هو الفقر الشديد. قال تعالى: (وَلَا تَقْتُلُوا أَوْلَادَكُمْ خَشْيَةَ إِمْلَاقٍ).' },

    // --- PART TWO: SHORT ANSWER (50 MARKS after modification) ---
    { id: 'arb-41', section: SectionType.SHORT_ANSWER, text: '41. حلل الأفكار الرئيسة في الأبيات التالية:\n\nقُم لِلمُعَلِّمِ وَفِّهِ التَبجيلا * كادَ المُعَلِّمُ أَن يَكونَ رَسولا\nأَعَلِمتَ أَشرَفَ أَو أَجَلَّ مِنَ الَّذي * يَبني وَيُنشِئُ أَنفُسًا وَعُقولا\nسُبحانَكَ اللَهُمَّ خَيرَ مُعَلِّمٍ * عَلَّمتَ بِالقَلَمِ القُرونَ الأولى\nأَخرَجتَ هذا العَقلَ مِن ظُلُماتِهِ * وَهَدَيتَهُ النورَ المُبينَ سَبيلا', type: 'text', correctAnswer: 'الأفكار الرئيسة: 1. تعظيم مكانة المعلم واحترامه. 2. المعلم يؤدي رسالة سامية تشبه رسالة الأنبياء. 3. المعلم هو باني العقول والنفوس. 4. الله سبحانه وتعالى هو المعلم الأول للبشرية. 5. العلم نور يخرج العقل من ظلمات الجهل.', marks: 4, topic: 'Analysis', explanation: 'يتطلب التحليل استخراج المعاني الجوهرية وصياغتها بنقاط واضحة.' },
    { id: 'arb-42', section: SectionType.SHORT_ANSWER, text: '42. استخدم الكلمات الآتية في جمل مفيدة بحيث يكون كل منها مشبَّهًا به:\nأ- البعوضة\nب- الأسد\nج- العسل\nد- البرق', type: 'text', correctAnswer: 'أ- العدو كالبعوضة في الإزعاج. ب- الجندي كالأسد في الشجاعة. ج- الكلام الطيب كالعسل في الحلاوة. د- الحصان كالبرق في السرعة.', marks: 6, topic: 'Rhetoric', explanation: 'يجب وضع الكلمة في جملة تشبيه بحيث تقع موقع المشبه به (بعد أداة التشبيه غالباً).' },
    { id: 'arb-43', section: SectionType.SHORT_ANSWER, text: '43. هات من عندك جملة فيها أسلوب القصر.', type: 'text', correctAnswer: 'ما محمد إلا رسول. (قصر موصوف على صفة). أو: إنما الحياة كفاح.', marks: 4, topic: 'Rhetoric', explanation: 'استخدام أدوات القصر مثل (إنما) أو (النفي والاستثناء).' },
    { id: 'arb-44', section: SectionType.SHORT_ANSWER, text: '44. عدد عوامل نهضة الأدب العربي في العصر الحديث.', type: 'text', correctAnswer: '1. انتشار الطباعة. 2. ظهور الصحافة. 3. إحياء التراث العربي. 4. انتشار التعليم وإنشاء المدارس. 5. الجمعيات الأدبية.', marks: 4, topic: 'Literature', explanation: 'عوامل النهضة الداخلية تشمل الطباعة والصحافة والتعليم والجمعيات الأدبية وإحياء التراث، مع التركيز على العوامل الذاتية.' },
    { id: 'arb-45', section: SectionType.SHORT_ANSWER, text: '45. كوّن جملة فيها نعت سببي.', type: 'text', correctAnswer: 'هذا رجلٌ كريمٌ خلقُهُ. أو: زرتُ حديقةً جميلةً أزهارُها.', marks: 3, topic: 'Grammar', explanation: 'النعت السببي يتبع ما قبله في الإعراب والتعريف/التنكير، ويتبع ما بعده في التذكير والتأنيث، ويرفع الاسم الظاهر بعده.' },
    { id: 'arb-46', section: SectionType.SHORT_ANSWER, text: '46. أعرب ما تحته خط (الكلمات بين قوسين) في الجمل الآتية:\n\nأ- اعتصم على (الكتاب)\nب- ما حضرت (منذ يوم) الإثنين\nج- صعد عمر (على المنبر)', type: 'text', correctAnswer: 'أ. الكتاب: اسم مجرور وعلامة جره الكسرة الظاهرة.\nب. منذ: ظرف زمان مبني على الضم في محل نصب. يوم: مضاف إليه مجرور وعلامة جره الكسرة.\nج. على المنبر: جار ومجرور.', marks: 5, topic: 'Grammar', explanation: 'إعراب المفردات حسب موقعها في الجملة.' },
    { id: 'arb-47', section: SectionType.SHORT_ANSWER, text: '47. زن الكلمات الآتية: مسرع ، كاتب، شكور، مقدام ، تواب', type: 'text', correctAnswer: 'مسرع: مُفْعِل. كاتب: فاعل. شكور: فَعُول. مقدام: مِفْعَال. تواب: فَعَّال.', marks: 5, topic: 'Morphology', explanation: 'الميزان الصرفي يعتمد على أصول الكلمة (ف ع ل) مع الزيادة.' },
    { id: 'arb-48', section: SectionType.SHORT_ANSWER, text: '48. استعمل الكلمات الآتية في جمل مفيدة من عندك:\nأ- الرزق\nب- السعادة\nج- المرض\nد- التقوى\nهـ- الغابات', type: 'text', correctAnswer: 'الرزق بيد الله. السعادة هدف كل إنسان. الوقاية خير من المرض. التقوى ميزان التفاضل. الغابات رئة الأرض.', marks: 5, topic: 'Composition', explanation: 'وضع الكلمات في سياق لغوي سليم ومفيد.' },
    { id: 'arb-49', section: SectionType.SHORT_ANSWER, text: '49. أعرب هذه الجملة:\n"شرب الولد اللبن"', type: 'text', correctAnswer: 'شربَ: فعل ماضٍ مبني على الفتح. الولدُ: فاعل مرفوع وعلامة رفعه الضمة الظاهرة. اللبنَ: مفعول به منصوب وعلامة نصبه الفتحة الظاهرة.', marks: 5, topic: 'Grammar', explanation: 'إعراب الجملة الفعلية البسيطة (فعل + فاعل + مفعول به).' },
    { id: 'arb-50', section: SectionType.SHORT_ANSWER, text: '50. برأيك، حدد الجماليات البديعية في البيت: "إن الرسول لنور يستضاء به ... مهند من سيوف الله مسلول"', type: 'text', correctAnswer: 'تشبيه بليغ: شبه الرسول بالنور (إن الرسول لنور). وتشبيه آخر: شبه الرسول بالسيف (مهند). الغرض: بيان عظمة الرسول وهدايته وقوته في الحق.', marks: 4, topic: 'Rhetoric', explanation: 'استخراج الصور البيانية (التشبيه) وتوضيح أركانها.' },

    // --- PART THREE: ESSAY (10 MARKS) ---
    { id: 'arb-51', section: SectionType.ESSAY, text: '51. تحدث عن أحد الموضوعات الآتية، على ألا يقل عن عشرة أسطر، مع مراعاة عناصر الموضوع:\n1- العدل في الإسلام\n2- التعليم بين الماضي والحاضر\n3- القراءة وأهميتها', type: 'text', correctAnswer: 'يُقيَّم حسب: 1. المقدمة والعرض والخاتمة. 2. سلامة اللغة والإملاء. 3. تسلسل الأفكار وترابطها. 4. الاستشهاد بالنصوص (قرآن، حديث، شعر). 5. جمال الأسلوب.', marks: 10, topic: 'Composition', explanation: 'كتابة مقال متكامل العناصر.' }
  ]
};

export const getExam = (year: number | null, subject: string | null): Exam | null => {
  if (year === 2025 && subject === 'Physics') {
    return PHYSICS_2025_EXAM;
  }
  if (year === 2025 && subject === 'Arabic Language') {
    return ARABIC_2025_EXAM;
  }
  return null;
};